// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for
/// [SecurityCenterManagement.CreateEventThreatDetectionCustomModule][google.cloud.securitycentermanagement.v1.SecurityCenterManagement.CreateEventThreatDetectionCustomModule].
///
/// [google.cloud.securitycentermanagement.v1.SecurityCenterManagement.CreateEventThreatDetectionCustomModule]: <doc:SecurityCenterManagementClient/createEventThreatDetectionCustomModule(request:options:)>
public struct CreateEventThreatDetectionCustomModuleRequest: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// Required. Name of parent for the module, in one of the following formats:
  ///
  /// * `organizations/{organization}/locations/{location}`
  /// * `folders/{folder}/locations/{location}`
  /// * `projects/{project}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Required. The module to create. The
  /// [EventThreatDetectionCustomModule.name][google.cloud.securitycentermanagement.v1.EventThreatDetectionCustomModule.name]
  /// field is ignored; Security Command Center generates the name.
  ///
  /// [google.cloud.securitycentermanagement.v1.EventThreatDetectionCustomModule.name]: <doc:EventThreatDetectionCustomModule/name>
  public var eventThreatDetectionCustomModule: EventThreatDetectionCustomModule? = nil

  /// Optional. When set to `true`, the request will be validated (including IAM
  /// checks), but no module will be created. An `OK` response indicates that the
  /// request is valid, while an error response indicates that the request is
  /// invalid.
  ///
  /// If the request is valid, a subsequent request to create the module could
  /// still fail for one of the following reasons:
  ///
  /// *  The state of your cloud resources changed; for example, you lost a
  ///    required IAM permission
  /// *  An error occurred during creation of the module
  ///
  /// Defaults to `false`.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `CreateEventThreatDetectionCustomModuleRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateEventThreatDetectionCustomModuleRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.securitycentermanagement.v1.CreateEventThreatDetectionCustomModuleRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
