// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [SecurityCenterManagement.DeleteSecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.SecurityCenterManagement.DeleteSecurityHealthAnalyticsCustomModule].
///
/// [google.cloud.securitycentermanagement.v1.SecurityCenterManagement.DeleteSecurityHealthAnalyticsCustomModule]: <doc:SecurityCenterManagementClient/deleteSecurityHealthAnalyticsCustomModule(request:options:)>
public struct DeleteSecurityHealthAnalyticsCustomModuleRequest: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// Required. The resource name of the SHA custom module, in one of the
  /// following formats:
  ///
  ///   * `organizations/{organization}/locations/{location}/securityHealthAnalyticsCustomModules/{custom_module}`
  ///   * `folders/{folder}/locations/{location}/securityHealthAnalyticsCustomModules/{custom_module}`
  ///   * `projects/{project}/locations/{location}/securityHealthAnalyticsCustomModules/{custom_module}`
  public var name: Swift.String = Swift.String()

  /// Optional. When set to `true`, the request will be validated (including IAM
  /// checks), but no module will be deleted. An `OK` response indicates that the
  /// request is valid, while an error response indicates that the request is
  /// invalid.
  ///
  /// If the request is valid, a subsequent request to delete the module could
  /// still fail for one of the following reasons:
  ///
  /// *  The state of your cloud resources changed; for example, you lost a
  ///    required IAM permission
  /// *  An error occurred during deletion of the module
  ///
  /// Defaults to `false`.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `DeleteSecurityHealthAnalyticsCustomModuleRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeleteSecurityHealthAnalyticsCustomModuleRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.securitycentermanagement.v1.DeleteSecurityHealthAnalyticsCustomModuleRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
