// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A Security Command Center resource that contains the configuration and
/// enablement state of a custom module, which enables Event Threat Detection to
/// write certain findings to Security Command Center.
public struct EventThreatDetectionCustomModule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the Event Threat Detection custom module,
  /// in one of the following formats:
  ///
  /// * `organizations/{organization}/locations/{location}/eventThreatDetectionCustomModules/{custom_module}`
  /// * `folders/{folder}/locations/{location}/eventThreatDetectionCustomModules/{custom_module}`
  /// * `projects/{project}/locations/{location}/eventThreatDetectionCustomModules/{custom_module}`
  public var name: Swift.String = Swift.String()

  /// Optional. Configuration for the module. For the resident module, its
  /// configuration value is defined at this level. For the inherited module, its
  /// configuration value is inherited from the ancestor module.
  public var config: GoogleCloudWkt.Struct? = nil

  /// Output only. The closest ancestor module that this module inherits the
  /// enablement state from. If empty, indicates that the custom module was
  /// created in the requesting parent organization, folder, or project. The
  /// format is the same as the custom module's resource name.
  public var ancestorModule: Swift.String = Swift.String()

  /// Optional. The state of enablement for the module at the given level of the
  /// hierarchy.
  public var enablementState: EventThreatDetectionCustomModule.EnablementState =
    EventThreatDetectionCustomModule.EnablementState()

  /// Optional. Type for the module. For example, `CONFIGURABLE_BAD_IP`.
  public var type: Swift.String = Swift.String()

  /// Optional. The human-readable name of the module.
  public var displayName: Swift.String = Swift.String()

  /// Optional. A description of the module.
  public var description: Swift.String = Swift.String()

  /// Output only. The time the module was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The editor the module was last updated by.
  public var lastEditor: Swift.String = Swift.String()

  /// Initialize a new instance of `EventThreatDetectionCustomModule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EventThreatDetectionCustomModule().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The enablement state of the module.
  public enum EnablementState: Codable, Equatable, Sendable {
    /// Unspecified enablement state.
    case unspecified
    /// The module is enabled at the given level.
    case enabled
    /// The module is disabled at the given level.
    case disabled
    /// State is inherited from an ancestor module. The module will either be
    /// effectively `ENABLED` or `DISABLED` based on its closest non-inherited
    /// ancestor module in the CRM hierarchy. If you try to set a top-level
    /// module (a module with no parent) to the `INHERITED` state, you receive an
    /// `INVALID_ARGUMENT` error.
    case inherited
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .enabled: return 1
      case .disabled: return 2
      case .inherited: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ENABLEMENT_STATE_UNSPECIFIED"
      case .enabled: return "ENABLED"
      case .disabled: return "DISABLED"
      case .inherited: return "INHERITED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EnablementState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ENABLEMENT_STATE_UNSPECIFIED": self = .unspecified
      case "ENABLED": self = .enabled
      case "DISABLED": self = .disabled
      case "INHERITED": self = .inherited
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EnablementState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .enabled
      case 2: self = .disabled
      case 3: self = .inherited
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .enabled: return try container.encode(1)
      case .disabled: return try container.encode(2)
      case .inherited: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.securitycentermanagement.v1.EventThreatDetectionCustomModule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
