// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for
/// [SecurityCenterManagement.GetSecurityCenterService][google.cloud.securitycentermanagement.v1.SecurityCenterManagement.GetSecurityCenterService].
///
/// [google.cloud.securitycentermanagement.v1.SecurityCenterManagement.GetSecurityCenterService]: <doc:SecurityCenterManagementClient/getSecurityCenterService(request:options:)>
public struct GetSecurityCenterServiceRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The Security Command Center service to retrieve, in one of the
  /// following formats:
  ///
  /// * organizations/{organization}/locations/{location}/securityCenterServices/{service}
  /// * folders/{folder}/locations/{location}/securityCenterServices/{service}
  /// * projects/{project}/locations/{location}/securityCenterServices/{service}
  ///
  /// The following values are valid for `{service}`:
  ///
  /// * `container-threat-detection`
  /// * `event-threat-detection`
  /// * `security-health-analytics`
  /// * `vm-threat-detection`
  /// * `web-security-scanner`
  public var name: Swift.String = Swift.String()

  /// Set to `true` to show only modules that are in scope. By default, all
  /// modules are shown.
  public var showEligibleModulesOnly: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `GetSecurityCenterServiceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GetSecurityCenterServiceRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.securitycentermanagement.v1.GetSecurityCenterServiceRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
