// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleGax
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response message for
/// [SecurityCenterManagement.ListEffectiveEventThreatDetectionCustomModules][google.cloud.securitycentermanagement.v1.SecurityCenterManagement.ListEffectiveEventThreatDetectionCustomModules].
///
/// [google.cloud.securitycentermanagement.v1.SecurityCenterManagement.ListEffectiveEventThreatDetectionCustomModules]: <doc:SecurityCenterManagementClient/listEffectiveEventThreatDetectionCustomModules(request:options:)>
public struct ListEffectiveEventThreatDetectionCustomModulesResponse: Codable, Equatable, GoogleWKT
    ._AnyPackable,
  Sendable
{
  /// The list of effective Event Threat Detection custom modules.
  public var effectiveEventThreatDetectionCustomModules:
    [EffectiveEventThreatDetectionCustomModule] = []

  /// A pagination token. To retrieve the next page of results, call the method
  /// again with this token.
  public var nextPageToken: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListEffectiveEventThreatDetectionCustomModulesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListEffectiveEventThreatDetectionCustomModulesResponse().with { $0.effectiveEventThreatDetectionCustomModules = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let effectiveEventThreatDetectionCustomModules = CodingKeys(
      stringValue: "effectiveEventThreatDetectionCustomModules")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")

    static let _knownKeys: Set<Swift.String> = [
      "effectiveEventThreatDetectionCustomModules",
      "nextPageToken",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [EffectiveEventThreatDetectionCustomModule].self,
      forKey: .effectiveEventThreatDetectionCustomModules)
    {
      self.effectiveEventThreatDetectionCustomModules = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(
      self.effectiveEventThreatDetectionCustomModules,
      forKey: .effectiveEventThreatDetectionCustomModules)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.securitycentermanagement.v1.ListEffectiveEventThreatDetectionCustomModulesResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}

@_spi(GoogleCloudInternal)
extension ListEffectiveEventThreatDetectionCustomModulesResponse: GoogleGax._PaginatedResponse {
  public func _getPaginatedItems() -> [EffectiveEventThreatDetectionCustomModule] {
    return self.effectiveEventThreatDetectionCustomModules
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
