// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for
/// [SecurityCenterManagement.ListEffectiveEventThreatDetectionCustomModules][google.cloud.securitycentermanagement.v1.SecurityCenterManagement.ListEffectiveEventThreatDetectionCustomModules].
///
/// [google.cloud.securitycentermanagement.v1.SecurityCenterManagement.ListEffectiveEventThreatDetectionCustomModules]: <doc:SecurityCenterManagementClient/listEffectiveEventThreatDetectionCustomModules(request:options:)>
public struct ListEffectiveEventThreatDetectionCustomModulesRequest: Codable, Equatable,
  GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Name of parent to list effective custom modules, in one of the
  /// following formats:
  ///
  /// * `organizations/{organization}/locations/{location}`
  /// * `folders/{folder}/locations/{location}`
  /// * `projects/{project}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of results to return in a single response.
  /// Default is 10, minimum is 1, maximum is 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A pagination token returned from a previous request. Provide this
  /// token to retrieve the next page of results.
  ///
  /// When paginating, the rest of the request must match the request that
  /// generated the page token.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListEffectiveEventThreatDetectionCustomModulesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListEffectiveEventThreatDetectionCustomModulesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.securitycentermanagement.v1.ListEffectiveEventThreatDetectionCustomModulesRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
