// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleGax
@_spi(GoogleCloudInternal) import GoogleWKT

/// Response message for
/// [SecurityCenterManagement.ListDescendantEventThreatDetectionCustomModules][google.cloud.securitycentermanagement.v1.SecurityCenterManagement.ListDescendantEventThreatDetectionCustomModules].
///
/// [google.cloud.securitycentermanagement.v1.SecurityCenterManagement.ListDescendantEventThreatDetectionCustomModules]: <doc:SecurityCenterManagementClient/listDescendantEventThreatDetectionCustomModules(request:options:)>
public struct ListDescendantEventThreatDetectionCustomModulesResponse: Codable, Equatable, GoogleWKT
    ._AnyPackable,
  GoogleGax._PaginatedResponse,
  Sendable
{
  /// The list of custom modules.
  public var eventThreatDetectionCustomModules: [EventThreatDetectionCustomModule] = []

  /// A pagination token. To retrieve the next page of results, call the method
  /// again with this token.
  public var nextPageToken: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListDescendantEventThreatDetectionCustomModulesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListDescendantEventThreatDetectionCustomModulesResponse().with { $0.eventThreatDetectionCustomModules = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let eventThreatDetectionCustomModules = CodingKeys(
      stringValue: "eventThreatDetectionCustomModules")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")

    static let _knownKeys: Set<Swift.String> = [
      "eventThreatDetectionCustomModules",
      "nextPageToken",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [EventThreatDetectionCustomModule].self, forKey: .eventThreatDetectionCustomModules)
    {
      self.eventThreatDetectionCustomModules = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(
      self.eventThreatDetectionCustomModules, forKey: .eventThreatDetectionCustomModules)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.securitycentermanagement.v1.ListDescendantEventThreatDetectionCustomModulesResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [EventThreatDetectionCustomModule] {
    return self.eventThreatDetectionCustomModules
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
