// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents a particular Security Command Center service. This includes
/// settings information such as top-level enablement in addition to individual
/// module settings. Service settings can be configured at the organization,
/// folder, or project level. Service settings at the organization or folder
/// level are inherited by those in descendant folders and projects.
public struct SecurityCenterService: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the service, in one of the following formats:
  ///
  /// * `organizations/{organization}/locations/{location}/securityCenterServices/{service}`
  /// * `folders/{folder}/locations/{location}/securityCenterServices/{service}`
  /// * `projects/{project}/locations/{location}/securityCenterServices/{service}`
  ///
  /// The following values are valid for `{service}`:
  ///
  /// * `container-threat-detection`
  /// * `event-threat-detection`
  /// * `security-health-analytics`
  /// * `vm-threat-detection`
  /// * `web-security-scanner`
  public var name: Swift.String = Swift.String()

  /// Optional. The intended enablement state for the service at its level of the
  /// resource hierarchy. A `DISABLED` state will override all module enablement
  /// states to `DISABLED`.
  public var intendedEnablementState: SecurityCenterService.EnablementState =
    SecurityCenterService.EnablementState()

  /// Output only. The effective enablement state for the service at its level of
  /// the resource hierarchy. If the intended state is set to `INHERITED`, the
  /// effective state will be inherited from the enablement state of an ancestor.
  /// This state may differ from the intended enablement state due to billing
  /// eligibility or onboarding status.
  public var effectiveEnablementState: SecurityCenterService.EnablementState =
    SecurityCenterService.EnablementState()

  /// Optional. The module configurations, including the enablement state for the
  /// service's modules. The absence of a module in the map implies that its
  /// configuration is inherited from its parents.
  public var modules: [Swift.String: SecurityCenterService.ModuleSettings] = [:]

  /// Output only. The time the service was last updated. This could be due to an
  /// explicit user update or due to a side effect of another system change, such
  /// as billing subscription expiry.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. Additional service-specific configuration. Not all services will
  /// utilize this field.
  public var serviceConfig: GoogleCloudWKT.Struct? = nil

  /// Initialize a new instance of `SecurityCenterService`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SecurityCenterService().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The settings for individual modules.
  public struct ModuleSettings: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. The intended enablement state for the module at its level of
    /// the resource hierarchy.
    public var intendedEnablementState: SecurityCenterService.EnablementState =
      SecurityCenterService.EnablementState()

    /// Output only. The effective enablement state for the module at its level
    /// of the resource hierarchy. If the intended state is set to `INHERITED`,
    /// the effective state will be inherited from the enablement state of an
    /// ancestor. This state may differ from the intended enablement state due to
    /// billing eligibility or onboarding status.
    public var effectiveEnablementState: SecurityCenterService.EnablementState =
      SecurityCenterService.EnablementState()

    /// Initialize a new instance of `ModuleSettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ModuleSettings().with { $0.intendedEnablementState = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.securitycentermanagement.v1.SecurityCenterService.ModuleSettings"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Represents the possible enablement states for a service or module.
  public enum EnablementState: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// State is inherited from the parent resource. Valid as an intended
    /// enablement state, but not as an effective enablement state.
    case inherited
    /// State is enabled.
    case enabled
    /// State is disabled.
    case disabled
    /// Security Command Center is configured to ingest findings from this
    /// service, but not to enable this service. This state indicates that
    /// Security Command Center is misconfigured. You can't set this state
    /// yourself.
    case ingestOnly
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .inherited: return 1
      case .enabled: return 2
      case .disabled: return 3
      case .ingestOnly: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ENABLEMENT_STATE_UNSPECIFIED"
      case .inherited: return "INHERITED"
      case .enabled: return "ENABLED"
      case .disabled: return "DISABLED"
      case .ingestOnly: return "INGEST_ONLY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EnablementState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ENABLEMENT_STATE_UNSPECIFIED": self = .unspecified
      case "INHERITED": self = .inherited
      case "ENABLED": self = .enabled
      case "DISABLED": self = .disabled
      case "INGEST_ONLY": self = .ingestOnly
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EnablementState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .inherited
      case 2: self = .enabled
      case 3: self = .disabled
      case 4: self = .ingestOnly
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .inherited: return try container.encode(1)
      case .enabled: return try container.encode(2)
      case .disabled: return try container.encode(3)
      case .ingestOnly: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycentermanagement.v1.SecurityCenterService"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
