// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class SecurityCenterManagementLogging: SecurityCenterManagementStub {
    let inner: any SecurityCenterManagementStub
    let logger: Logger

    public init(_ inner: any SecurityCenterManagementStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-securitycentermanagement-v1"
      logger[metadataKey: "gcp.client.service"] = "securitycentermanagement"
      logger[metadataKey: "gcp.experimental.swift.client"] = "SecurityCenterManagement"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listEffectiveSecurityHealthAnalyticsCustomModules(
      request: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListEffectiveSecurityHealthAnalyticsCustomModulesResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEffectiveSecurityHealthAnalyticsCustomModules",
        action: {
          (
            r: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest,
            o: GoogleCloudGax.RequestOptions
          ) async throws
            -> GoogleCloudSecurityCenterManagementV1
            .ListEffectiveSecurityHealthAnalyticsCustomModulesResponse
          in
          return try await self.inner.listEffectiveSecurityHealthAnalyticsCustomModules(
            request: r, options: o)
        })
    }

    public func getEffectiveSecurityHealthAnalyticsCustomModule(
      request: GetEffectiveSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.EffectiveSecurityHealthAnalyticsCustomModule
    {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEffectiveSecurityHealthAnalyticsCustomModule",
        action: {
          (
            r: GetEffectiveSecurityHealthAnalyticsCustomModuleRequest,
            o: GoogleCloudGax.RequestOptions
          ) async throws
            -> GoogleCloudSecurityCenterManagementV1.EffectiveSecurityHealthAnalyticsCustomModule
          in
          return try await self.inner.getEffectiveSecurityHealthAnalyticsCustomModule(
            request: r, options: o)
        })
    }

    public func listSecurityHealthAnalyticsCustomModules(
      request: ListSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ListSecurityHealthAnalyticsCustomModulesResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSecurityHealthAnalyticsCustomModules",
        action: {
          (r: ListSecurityHealthAnalyticsCustomModulesRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1
            .ListSecurityHealthAnalyticsCustomModulesResponse
          in
          return try await self.inner.listSecurityHealthAnalyticsCustomModules(
            request: r, options: o)
        })
    }

    public func listDescendantSecurityHealthAnalyticsCustomModules(
      request: ListDescendantSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListDescendantSecurityHealthAnalyticsCustomModulesResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDescendantSecurityHealthAnalyticsCustomModules",
        action: {
          (
            r: ListDescendantSecurityHealthAnalyticsCustomModulesRequest,
            o: GoogleCloudGax.RequestOptions
          ) async throws
            -> GoogleCloudSecurityCenterManagementV1
            .ListDescendantSecurityHealthAnalyticsCustomModulesResponse
          in
          return try await self.inner.listDescendantSecurityHealthAnalyticsCustomModules(
            request: r, options: o)
        })
    }

    public func getSecurityHealthAnalyticsCustomModule(
      request: GetSecurityHealthAnalyticsCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSecurityHealthAnalyticsCustomModule",
        action: {
          (r: GetSecurityHealthAnalyticsCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule
          in
          return try await self.inner.getSecurityHealthAnalyticsCustomModule(request: r, options: o)
        })
    }

    public func createSecurityHealthAnalyticsCustomModule(
      request: CreateSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
      try await self._intercept(
        request: request,
        options: options,
        name: "createSecurityHealthAnalyticsCustomModule",
        action: {
          (r: CreateSecurityHealthAnalyticsCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule
          in
          return try await self.inner.createSecurityHealthAnalyticsCustomModule(
            request: r, options: o)
        })
    }

    public func updateSecurityHealthAnalyticsCustomModule(
      request: UpdateSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSecurityHealthAnalyticsCustomModule",
        action: {
          (r: UpdateSecurityHealthAnalyticsCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule
          in
          return try await self.inner.updateSecurityHealthAnalyticsCustomModule(
            request: r, options: o)
        })
    }

    public func deleteSecurityHealthAnalyticsCustomModule(
      request: DeleteSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSecurityHealthAnalyticsCustomModule",
        action: {
          (r: DeleteSecurityHealthAnalyticsCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteSecurityHealthAnalyticsCustomModule(
            request: r, options: o)
        })
    }

    public func simulateSecurityHealthAnalyticsCustomModule(
      request: SimulateSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.SimulateSecurityHealthAnalyticsCustomModuleResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        name: "simulateSecurityHealthAnalyticsCustomModule",
        action: {
          (r: SimulateSecurityHealthAnalyticsCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1
            .SimulateSecurityHealthAnalyticsCustomModuleResponse
          in
          return try await self.inner.simulateSecurityHealthAnalyticsCustomModule(
            request: r, options: o)
        })
    }

    public func listEffectiveEventThreatDetectionCustomModules(
      request: ListEffectiveEventThreatDetectionCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListEffectiveEventThreatDetectionCustomModulesResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEffectiveEventThreatDetectionCustomModules",
        action: {
          (
            r: ListEffectiveEventThreatDetectionCustomModulesRequest,
            o: GoogleCloudGax.RequestOptions
          ) async throws
            -> GoogleCloudSecurityCenterManagementV1
            .ListEffectiveEventThreatDetectionCustomModulesResponse
          in
          return try await self.inner.listEffectiveEventThreatDetectionCustomModules(
            request: r, options: o)
        })
    }

    public func getEffectiveEventThreatDetectionCustomModule(
      request: GetEffectiveEventThreatDetectionCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.EffectiveEventThreatDetectionCustomModule
    {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEffectiveEventThreatDetectionCustomModule",
        action: {
          (r: GetEffectiveEventThreatDetectionCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1.EffectiveEventThreatDetectionCustomModule
          in
          return try await self.inner.getEffectiveEventThreatDetectionCustomModule(
            request: r, options: o)
        })
    }

    public func listEventThreatDetectionCustomModules(
      request: ListEventThreatDetectionCustomModulesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ListEventThreatDetectionCustomModulesResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        name: "listEventThreatDetectionCustomModules",
        action: {
          (r: ListEventThreatDetectionCustomModulesRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1.ListEventThreatDetectionCustomModulesResponse
          in
          return try await self.inner.listEventThreatDetectionCustomModules(request: r, options: o)
        })
    }

    public func listDescendantEventThreatDetectionCustomModules(
      request: ListDescendantEventThreatDetectionCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListDescendantEventThreatDetectionCustomModulesResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDescendantEventThreatDetectionCustomModules",
        action: {
          (
            r: ListDescendantEventThreatDetectionCustomModulesRequest,
            o: GoogleCloudGax.RequestOptions
          ) async throws
            -> GoogleCloudSecurityCenterManagementV1
            .ListDescendantEventThreatDetectionCustomModulesResponse
          in
          return try await self.inner.listDescendantEventThreatDetectionCustomModules(
            request: r, options: o)
        })
    }

    public func getEventThreatDetectionCustomModule(
      request: GetEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEventThreatDetectionCustomModule",
        action: {
          (r: GetEventThreatDetectionCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule
          in
          return try await self.inner.getEventThreatDetectionCustomModule(request: r, options: o)
        })
    }

    public func createEventThreatDetectionCustomModule(
      request: CreateEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
      try await self._intercept(
        request: request,
        options: options,
        name: "createEventThreatDetectionCustomModule",
        action: {
          (r: CreateEventThreatDetectionCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule
          in
          return try await self.inner.createEventThreatDetectionCustomModule(request: r, options: o)
        })
    }

    public func updateEventThreatDetectionCustomModule(
      request: UpdateEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateEventThreatDetectionCustomModule",
        action: {
          (r: UpdateEventThreatDetectionCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule
          in
          return try await self.inner.updateEventThreatDetectionCustomModule(request: r, options: o)
        })
    }

    public func deleteEventThreatDetectionCustomModule(
      request: DeleteEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteEventThreatDetectionCustomModule",
        action: {
          (r: DeleteEventThreatDetectionCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteEventThreatDetectionCustomModule(request: r, options: o)
        })
    }

    public func validateEventThreatDetectionCustomModule(
      request: ValidateEventThreatDetectionCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ValidateEventThreatDetectionCustomModuleResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        name: "validateEventThreatDetectionCustomModule",
        action: {
          (r: ValidateEventThreatDetectionCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1
            .ValidateEventThreatDetectionCustomModuleResponse
          in
          return try await self.inner.validateEventThreatDetectionCustomModule(
            request: r, options: o)
        })
    }

    public func getSecurityCenterService(
      request: GetSecurityCenterServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSecurityCenterService",
        action: {
          (r: GetSecurityCenterServiceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService
          in
          return try await self.inner.getSecurityCenterService(request: r, options: o)
        })
    }

    public func listSecurityCenterServices(
      request: ListSecurityCenterServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.ListSecurityCenterServicesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSecurityCenterServices",
        action: {
          (r: ListSecurityCenterServicesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterManagementV1.ListSecurityCenterServicesResponse
          in
          return try await self.inner.listSecurityCenterServices(request: r, options: o)
        })
    }

    public func updateSecurityCenterService(
      request: UpdateSecurityCenterServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSecurityCenterService",
        action: {
          (r: UpdateSecurityCenterServiceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService
          in
          return try await self.inner.updateSecurityCenterService(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
