// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class SecurityCenterManagementRetry: SecurityCenterManagementStub {
    let inner: any SecurityCenterManagementStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any SecurityCenterManagementStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listEffectiveSecurityHealthAnalyticsCustomModules(
      request: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListEffectiveSecurityHealthAnalyticsCustomModulesResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (
            r: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest,
            o: GoogleCloudGax.RequestOptions
          ) async throws
            -> GoogleCloudSecurityCenterManagementV1
            .ListEffectiveSecurityHealthAnalyticsCustomModulesResponse
          in
          return try await self.inner.listEffectiveSecurityHealthAnalyticsCustomModules(
            request: r, options: o)
        })
    }

    public func getEffectiveSecurityHealthAnalyticsCustomModule(
      request: GetEffectiveSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.EffectiveSecurityHealthAnalyticsCustomModule
    {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (
            r: GetEffectiveSecurityHealthAnalyticsCustomModuleRequest,
            o: GoogleCloudGax.RequestOptions
          ) async throws
            -> GoogleCloudSecurityCenterManagementV1.EffectiveSecurityHealthAnalyticsCustomModule
          in
          return try await self.inner.getEffectiveSecurityHealthAnalyticsCustomModule(
            request: r, options: o)
        })
    }

    public func listSecurityHealthAnalyticsCustomModules(
      request: ListSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ListSecurityHealthAnalyticsCustomModulesResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListSecurityHealthAnalyticsCustomModulesRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1
            .ListSecurityHealthAnalyticsCustomModulesResponse
          in
          return try await self.inner.listSecurityHealthAnalyticsCustomModules(
            request: r, options: o)
        })
    }

    public func listDescendantSecurityHealthAnalyticsCustomModules(
      request: ListDescendantSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListDescendantSecurityHealthAnalyticsCustomModulesResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (
            r: ListDescendantSecurityHealthAnalyticsCustomModulesRequest,
            o: GoogleCloudGax.RequestOptions
          ) async throws
            -> GoogleCloudSecurityCenterManagementV1
            .ListDescendantSecurityHealthAnalyticsCustomModulesResponse
          in
          return try await self.inner.listDescendantSecurityHealthAnalyticsCustomModules(
            request: r, options: o)
        })
    }

    public func getSecurityHealthAnalyticsCustomModule(
      request: GetSecurityHealthAnalyticsCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSecurityHealthAnalyticsCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule
          in
          return try await self.inner.getSecurityHealthAnalyticsCustomModule(request: r, options: o)
        })
    }

    public func createSecurityHealthAnalyticsCustomModule(
      request: CreateSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateSecurityHealthAnalyticsCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule
          in
          return try await self.inner.createSecurityHealthAnalyticsCustomModule(
            request: r, options: o)
        })
    }

    public func updateSecurityHealthAnalyticsCustomModule(
      request: UpdateSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateSecurityHealthAnalyticsCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule
          in
          return try await self.inner.updateSecurityHealthAnalyticsCustomModule(
            request: r, options: o)
        })
    }

    public func deleteSecurityHealthAnalyticsCustomModule(
      request: DeleteSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteSecurityHealthAnalyticsCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteSecurityHealthAnalyticsCustomModule(
            request: r, options: o)
        })
    }

    public func simulateSecurityHealthAnalyticsCustomModule(
      request: SimulateSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.SimulateSecurityHealthAnalyticsCustomModuleResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: SimulateSecurityHealthAnalyticsCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1
            .SimulateSecurityHealthAnalyticsCustomModuleResponse
          in
          return try await self.inner.simulateSecurityHealthAnalyticsCustomModule(
            request: r, options: o)
        })
    }

    public func listEffectiveEventThreatDetectionCustomModules(
      request: ListEffectiveEventThreatDetectionCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListEffectiveEventThreatDetectionCustomModulesResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (
            r: ListEffectiveEventThreatDetectionCustomModulesRequest,
            o: GoogleCloudGax.RequestOptions
          ) async throws
            -> GoogleCloudSecurityCenterManagementV1
            .ListEffectiveEventThreatDetectionCustomModulesResponse
          in
          return try await self.inner.listEffectiveEventThreatDetectionCustomModules(
            request: r, options: o)
        })
    }

    public func getEffectiveEventThreatDetectionCustomModule(
      request: GetEffectiveEventThreatDetectionCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.EffectiveEventThreatDetectionCustomModule
    {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetEffectiveEventThreatDetectionCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1.EffectiveEventThreatDetectionCustomModule
          in
          return try await self.inner.getEffectiveEventThreatDetectionCustomModule(
            request: r, options: o)
        })
    }

    public func listEventThreatDetectionCustomModules(
      request: ListEventThreatDetectionCustomModulesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ListEventThreatDetectionCustomModulesResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListEventThreatDetectionCustomModulesRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1.ListEventThreatDetectionCustomModulesResponse
          in
          return try await self.inner.listEventThreatDetectionCustomModules(request: r, options: o)
        })
    }

    public func listDescendantEventThreatDetectionCustomModules(
      request: ListDescendantEventThreatDetectionCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListDescendantEventThreatDetectionCustomModulesResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (
            r: ListDescendantEventThreatDetectionCustomModulesRequest,
            o: GoogleCloudGax.RequestOptions
          ) async throws
            -> GoogleCloudSecurityCenterManagementV1
            .ListDescendantEventThreatDetectionCustomModulesResponse
          in
          return try await self.inner.listDescendantEventThreatDetectionCustomModules(
            request: r, options: o)
        })
    }

    public func getEventThreatDetectionCustomModule(
      request: GetEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetEventThreatDetectionCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule
          in
          return try await self.inner.getEventThreatDetectionCustomModule(request: r, options: o)
        })
    }

    public func createEventThreatDetectionCustomModule(
      request: CreateEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateEventThreatDetectionCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule
          in
          return try await self.inner.createEventThreatDetectionCustomModule(request: r, options: o)
        })
    }

    public func updateEventThreatDetectionCustomModule(
      request: UpdateEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateEventThreatDetectionCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule
          in
          return try await self.inner.updateEventThreatDetectionCustomModule(request: r, options: o)
        })
    }

    public func deleteEventThreatDetectionCustomModule(
      request: DeleteEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteEventThreatDetectionCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteEventThreatDetectionCustomModule(request: r, options: o)
        })
    }

    public func validateEventThreatDetectionCustomModule(
      request: ValidateEventThreatDetectionCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ValidateEventThreatDetectionCustomModuleResponse
    {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ValidateEventThreatDetectionCustomModuleRequest, o: GoogleCloudGax.RequestOptions)
            async throws
            -> GoogleCloudSecurityCenterManagementV1
            .ValidateEventThreatDetectionCustomModuleResponse
          in
          return try await self.inner.validateEventThreatDetectionCustomModule(
            request: r, options: o)
        })
    }

    public func getSecurityCenterService(
      request: GetSecurityCenterServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSecurityCenterServiceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService
          in
          return try await self.inner.getSecurityCenterService(request: r, options: o)
        })
    }

    public func listSecurityCenterServices(
      request: ListSecurityCenterServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.ListSecurityCenterServicesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListSecurityCenterServicesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterManagementV1.ListSecurityCenterServicesResponse
          in
          return try await self.inner.listSecurityCenterServices(request: r, options: o)
        })
    }

    public func updateSecurityCenterService(
      request: UpdateSecurityCenterServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateSecurityCenterServiceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService
          in
          return try await self.inner.updateSecurityCenterService(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
