// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleWKT
import GoogleGax

extension Clients {
  protocol SecurityCenterManagementStub: Sendable {
    func listEffectiveSecurityHealthAnalyticsCustomModules(
      request: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListEffectiveSecurityHealthAnalyticsCustomModulesResponse

    func getEffectiveSecurityHealthAnalyticsCustomModule(
      request: GetEffectiveSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.EffectiveSecurityHealthAnalyticsCustomModule

    func listSecurityHealthAnalyticsCustomModules(
      request: ListSecurityHealthAnalyticsCustomModulesRequest, options: GoogleGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ListSecurityHealthAnalyticsCustomModulesResponse

    func listDescendantSecurityHealthAnalyticsCustomModules(
      request: ListDescendantSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListDescendantSecurityHealthAnalyticsCustomModulesResponse

    func getSecurityHealthAnalyticsCustomModule(
      request: GetSecurityHealthAnalyticsCustomModuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule

    func createSecurityHealthAnalyticsCustomModule(
      request: CreateSecurityHealthAnalyticsCustomModuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule

    func updateSecurityHealthAnalyticsCustomModule(
      request: UpdateSecurityHealthAnalyticsCustomModuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule

    func deleteSecurityHealthAnalyticsCustomModule(
      request: DeleteSecurityHealthAnalyticsCustomModuleRequest, options: GoogleGax.RequestOptions
    ) async throws

    func simulateSecurityHealthAnalyticsCustomModule(
      request: SimulateSecurityHealthAnalyticsCustomModuleRequest, options: GoogleGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.SimulateSecurityHealthAnalyticsCustomModuleResponse

    func listEffectiveEventThreatDetectionCustomModules(
      request: ListEffectiveEventThreatDetectionCustomModulesRequest,
      options: GoogleGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListEffectiveEventThreatDetectionCustomModulesResponse

    func getEffectiveEventThreatDetectionCustomModule(
      request: GetEffectiveEventThreatDetectionCustomModuleRequest,
      options: GoogleGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.EffectiveEventThreatDetectionCustomModule

    func listEventThreatDetectionCustomModules(
      request: ListEventThreatDetectionCustomModulesRequest, options: GoogleGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ListEventThreatDetectionCustomModulesResponse

    func listDescendantEventThreatDetectionCustomModules(
      request: ListDescendantEventThreatDetectionCustomModulesRequest,
      options: GoogleGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListDescendantEventThreatDetectionCustomModulesResponse

    func getEventThreatDetectionCustomModule(
      request: GetEventThreatDetectionCustomModuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule

    func createEventThreatDetectionCustomModule(
      request: CreateEventThreatDetectionCustomModuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule

    func updateEventThreatDetectionCustomModule(
      request: UpdateEventThreatDetectionCustomModuleRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule

    func deleteEventThreatDetectionCustomModule(
      request: DeleteEventThreatDetectionCustomModuleRequest, options: GoogleGax.RequestOptions
    ) async throws

    func validateEventThreatDetectionCustomModule(
      request: ValidateEventThreatDetectionCustomModuleRequest, options: GoogleGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ValidateEventThreatDetectionCustomModuleResponse

    func getSecurityCenterService(
      request: GetSecurityCenterServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService

    func listSecurityCenterServices(
      request: ListSecurityCenterServicesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.ListSecurityCenterServicesResponse

    func updateSecurityCenterService(
      request: UpdateSecurityCenterServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}
