// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class SecurityCenterManagementTransport: SecurityCenterManagementStub {
    let inner: GoogleCloudGax._HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://securitycentermanagement.googleapis.com",
      )
    }

    public func listEffectiveSecurityHealthAnalyticsCustomModules(
      request: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListEffectiveSecurityHealthAnalyticsCustomModulesResponse
    {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/effectiveSecurityHealthAnalyticsCustomModules"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1
          .ListEffectiveSecurityHealthAnalyticsCustomModulesResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func getEffectiveSecurityHealthAnalyticsCustomModule(
      request: GetEffectiveSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.EffectiveSecurityHealthAnalyticsCustomModule
    {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.EffectiveSecurityHealthAnalyticsCustomModule.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func listSecurityHealthAnalyticsCustomModules(
      request: ListSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ListSecurityHealthAnalyticsCustomModulesResponse
    {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/securityHealthAnalyticsCustomModules"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.ListSecurityHealthAnalyticsCustomModulesResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func listDescendantSecurityHealthAnalyticsCustomModules(
      request: ListDescendantSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListDescendantSecurityHealthAnalyticsCustomModulesResponse
    {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/securityHealthAnalyticsCustomModules:listDescendant"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1
          .ListDescendantSecurityHealthAnalyticsCustomModulesResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func getSecurityHealthAnalyticsCustomModule(
      request: GetSecurityHealthAnalyticsCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func createSecurityHealthAnalyticsCustomModule(
      request: CreateSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/securityHealthAnalyticsCustomModules"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.securityHealthAnalyticsCustomModule {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func updateSecurityHealthAnalyticsCustomModule(
      request: UpdateSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.securityHealthAnalyticsCustomModule.map({ $0.name }),
          !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.security_health_analytics_custom_module.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.securityHealthAnalyticsCustomModule {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func deleteSecurityHealthAnalyticsCustomModule(
      request: DeleteSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWkt.Empty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func simulateSecurityHealthAnalyticsCustomModule(
      request: SimulateSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.SimulateSecurityHealthAnalyticsCustomModuleResponse
    {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/securityHealthAnalyticsCustomModules:simulate"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.SimulateSecurityHealthAnalyticsCustomModuleResponse
          .self, timeout: options.attemptTimeout
      ).get()
    }

    public func listEffectiveEventThreatDetectionCustomModules(
      request: ListEffectiveEventThreatDetectionCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListEffectiveEventThreatDetectionCustomModulesResponse
    {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/effectiveEventThreatDetectionCustomModules"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.ListEffectiveEventThreatDetectionCustomModulesResponse
          .self, timeout: options.attemptTimeout
      ).get()
    }

    public func getEffectiveEventThreatDetectionCustomModule(
      request: GetEffectiveEventThreatDetectionCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.EffectiveEventThreatDetectionCustomModule
    {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.EffectiveEventThreatDetectionCustomModule.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func listEventThreatDetectionCustomModules(
      request: ListEventThreatDetectionCustomModulesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ListEventThreatDetectionCustomModulesResponse
    {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/eventThreatDetectionCustomModules"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.ListEventThreatDetectionCustomModulesResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func listDescendantEventThreatDetectionCustomModules(
      request: ListDescendantEventThreatDetectionCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListDescendantEventThreatDetectionCustomModulesResponse
    {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/eventThreatDetectionCustomModules:listDescendant"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1
          .ListDescendantEventThreatDetectionCustomModulesResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func getEventThreatDetectionCustomModule(
      request: GetEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func createEventThreatDetectionCustomModule(
      request: CreateEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/eventThreatDetectionCustomModules"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.eventThreatDetectionCustomModule {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func updateEventThreatDetectionCustomModule(
      request: UpdateEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.eventThreatDetectionCustomModule.map({ $0.name }),
          !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.event_threat_detection_custom_module.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.eventThreatDetectionCustomModule {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func deleteEventThreatDetectionCustomModule(
      request: DeleteEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.DELETE)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWkt.Empty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func validateEventThreatDetectionCustomModule(
      request: ValidateEventThreatDetectionCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ValidateEventThreatDetectionCustomModuleResponse
    {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/eventThreatDetectionCustomModules:validate"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.POST)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.ValidateEventThreatDetectionCustomModuleResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func getSecurityCenterService(
      request: GetSecurityCenterServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(
        contentsOf: try encoder.encode(
          request.showEligibleModulesOnly, prefix: "showEligibleModulesOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.SecurityCenterService.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func listSecurityCenterServices(
      request: ListSecurityCenterServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.ListSecurityCenterServicesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/securityCenterServices"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(
        contentsOf: try encoder.encode(
          request.showEligibleModulesOnly, prefix: "showEligibleModulesOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.ListSecurityCenterServicesResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func updateSecurityCenterService(
      request: UpdateSecurityCenterServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.securityCenterService.map({ $0.name }),
          !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.security_center_service.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.securityCenterService {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      return try await req.rpc(
        GoogleCloudSecurityCenterManagementV1.SecurityCenterService.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/locations"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax._QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudLocation.ListLocationsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudLocation.Location.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
