// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleCloudGax

/// Service describing handlers for resources
///
/// @Snippet(path: "SecurityCenterManagementQuickstart")
public class SecurityCenterManagementClient: Clients.SecurityCenterManagementProtocol {
  let inner: any Clients.SecurityCenterManagementStub

  /// Creates a new `SecurityCenterManagementClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.SecurityCenterManagementStub =
      try Clients.SecurityCenterManagementTransport(options)
    inner = Clients.SecurityCenterManagementRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.SecurityCenterManagementLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Returns a list of all
  /// [EffectiveSecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.EffectiveSecurityHealthAnalyticsCustomModule]
  /// resources for the given parent. This includes resident modules defined at
  /// the scope of the parent, and inherited modules, inherited from ancestor
  /// organizations, folders, and projects (no descendants).
  ///
  /// [google.cloud.securitycentermanagement.v1.EffectiveSecurityHealthAnalyticsCustomModule]: <doc:EffectiveSecurityHealthAnalyticsCustomModule>
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListEffectiveSecurityHealthAnalyticsCustomModules")
  public func listEffectiveSecurityHealthAnalyticsCustomModules(
    request: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1
    .ListEffectiveSecurityHealthAnalyticsCustomModulesResponse
  {
    try await self.inner.listEffectiveSecurityHealthAnalyticsCustomModules(
      request: request, options: options)
  }

  /// Returns a list of all
  /// [EffectiveSecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.EffectiveSecurityHealthAnalyticsCustomModule]
  /// resources for the given parent. This includes resident modules defined at
  /// the scope of the parent, and inherited modules, inherited from ancestor
  /// organizations, folders, and projects (no descendants).
  ///
  /// [google.cloud.securitycentermanagement.v1.EffectiveSecurityHealthAnalyticsCustomModule]: <doc:EffectiveSecurityHealthAnalyticsCustomModule>
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListEffectiveSecurityHealthAnalyticsCustomModules")
  public func listEffectiveSecurityHealthAnalyticsCustomModules(
    byItem: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<EffectiveSecurityHealthAnalyticsCustomModule, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityCenterManagementV1
        .ListEffectiveSecurityHealthAnalyticsCustomModulesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listEffectiveSecurityHealthAnalyticsCustomModules(
        request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single
  /// [EffectiveSecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.EffectiveSecurityHealthAnalyticsCustomModule].
  ///
  /// [google.cloud.securitycentermanagement.v1.EffectiveSecurityHealthAnalyticsCustomModule]: <doc:EffectiveSecurityHealthAnalyticsCustomModule>
  ///
  /// @Snippet(path: "SecurityCenterManagement_GetEffectiveSecurityHealthAnalyticsCustomModule")
  public func getEffectiveSecurityHealthAnalyticsCustomModule(
    request: GetEffectiveSecurityHealthAnalyticsCustomModuleRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.EffectiveSecurityHealthAnalyticsCustomModule
  {
    try await self.inner.getEffectiveSecurityHealthAnalyticsCustomModule(
      request: request, options: options)
  }

  /// Returns a list of all
  /// [SecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]
  /// resources for the given parent. This includes resident modules defined at
  /// the scope of the parent, and inherited modules, inherited from ancestor
  /// organizations, folders, and projects (no descendants).
  ///
  /// [google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]: <doc:SecurityHealthAnalyticsCustomModule>
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListSecurityHealthAnalyticsCustomModules")
  public func listSecurityHealthAnalyticsCustomModules(
    request: ListSecurityHealthAnalyticsCustomModulesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.ListSecurityHealthAnalyticsCustomModulesResponse
  {
    try await self.inner.listSecurityHealthAnalyticsCustomModules(
      request: request, options: options)
  }

  /// Returns a list of all
  /// [SecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]
  /// resources for the given parent. This includes resident modules defined at
  /// the scope of the parent, and inherited modules, inherited from ancestor
  /// organizations, folders, and projects (no descendants).
  ///
  /// [google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]: <doc:SecurityHealthAnalyticsCustomModule>
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListSecurityHealthAnalyticsCustomModules")
  public func listSecurityHealthAnalyticsCustomModules(
    byItem: ListSecurityHealthAnalyticsCustomModulesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SecurityHealthAnalyticsCustomModule, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityCenterManagementV1.ListSecurityHealthAnalyticsCustomModulesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listSecurityHealthAnalyticsCustomModules(
        request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Returns a list of all resident
  /// [SecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]
  /// resources under the given organization, folder, or project and all of its
  /// descendants.
  ///
  /// [google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]: <doc:SecurityHealthAnalyticsCustomModule>
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListDescendantSecurityHealthAnalyticsCustomModules")
  public func listDescendantSecurityHealthAnalyticsCustomModules(
    request: ListDescendantSecurityHealthAnalyticsCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1
    .ListDescendantSecurityHealthAnalyticsCustomModulesResponse
  {
    try await self.inner.listDescendantSecurityHealthAnalyticsCustomModules(
      request: request, options: options)
  }

  /// Returns a list of all resident
  /// [SecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]
  /// resources under the given organization, folder, or project and all of its
  /// descendants.
  ///
  /// [google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]: <doc:SecurityHealthAnalyticsCustomModule>
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListDescendantSecurityHealthAnalyticsCustomModules")
  public func listDescendantSecurityHealthAnalyticsCustomModules(
    byItem: ListDescendantSecurityHealthAnalyticsCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SecurityHealthAnalyticsCustomModule, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityCenterManagementV1
        .ListDescendantSecurityHealthAnalyticsCustomModulesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listDescendantSecurityHealthAnalyticsCustomModules(
        request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Retrieves a
  /// [SecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule].
  ///
  /// [google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]: <doc:SecurityHealthAnalyticsCustomModule>
  ///
  /// @Snippet(path: "SecurityCenterManagement_GetSecurityHealthAnalyticsCustomModule")
  public func getSecurityHealthAnalyticsCustomModule(
    request: GetSecurityHealthAnalyticsCustomModuleRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
    try await self.inner.getSecurityHealthAnalyticsCustomModule(request: request, options: options)
  }

  /// Creates a resident
  /// [SecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]
  /// at the scope of the given organization, folder, or project, and also
  /// creates inherited `SecurityHealthAnalyticsCustomModule` resources for all
  /// folders and projects that are descendants of the given parent. These
  /// modules are enabled by default.
  ///
  /// [google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]: <doc:SecurityHealthAnalyticsCustomModule>
  ///
  /// @Snippet(path: "SecurityCenterManagement_CreateSecurityHealthAnalyticsCustomModule")
  public func createSecurityHealthAnalyticsCustomModule(
    request: CreateSecurityHealthAnalyticsCustomModuleRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
    try await self.inner.createSecurityHealthAnalyticsCustomModule(
      request: request, options: options)
  }

  /// Updates the
  /// [SecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]
  /// under the given name based on the given update mask. Updating the
  /// enablement state is supported on both resident and inherited modules
  /// (though resident modules cannot have an enablement state of "inherited").
  /// Updating the display name and custom configuration of a module is supported
  /// on resident modules only.
  ///
  /// [google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]: <doc:SecurityHealthAnalyticsCustomModule>
  ///
  /// @Snippet(path: "SecurityCenterManagement_UpdateSecurityHealthAnalyticsCustomModule")
  public func updateSecurityHealthAnalyticsCustomModule(
    request: UpdateSecurityHealthAnalyticsCustomModuleRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
    try await self.inner.updateSecurityHealthAnalyticsCustomModule(
      request: request, options: options)
  }

  /// Deletes the specified
  /// [SecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]
  /// and all of its descendants in the resource hierarchy. This method is only
  /// supported for resident custom modules.
  ///
  /// [google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]: <doc:SecurityHealthAnalyticsCustomModule>
  ///
  /// @Snippet(path: "SecurityCenterManagement_DeleteSecurityHealthAnalyticsCustomModule")
  public func deleteSecurityHealthAnalyticsCustomModule(
    request: DeleteSecurityHealthAnalyticsCustomModuleRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteSecurityHealthAnalyticsCustomModule(
      request: request, options: options)
  }

  /// Simulates the result of using a
  /// [SecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]
  /// to check a resource.
  ///
  /// [google.cloud.securitycentermanagement.v1.SecurityHealthAnalyticsCustomModule]: <doc:SecurityHealthAnalyticsCustomModule>
  ///
  /// @Snippet(path: "SecurityCenterManagement_SimulateSecurityHealthAnalyticsCustomModule")
  public func simulateSecurityHealthAnalyticsCustomModule(
    request: SimulateSecurityHealthAnalyticsCustomModuleRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.SimulateSecurityHealthAnalyticsCustomModuleResponse
  {
    try await self.inner.simulateSecurityHealthAnalyticsCustomModule(
      request: request, options: options)
  }

  /// Lists all effective Event Threat Detection custom modules for the
  /// given parent. This includes resident modules defined at the scope of the
  /// parent along with modules inherited from its ancestors.
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListEffectiveEventThreatDetectionCustomModules")
  public func listEffectiveEventThreatDetectionCustomModules(
    request: ListEffectiveEventThreatDetectionCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.ListEffectiveEventThreatDetectionCustomModulesResponse
  {
    try await self.inner.listEffectiveEventThreatDetectionCustomModules(
      request: request, options: options)
  }

  /// Lists all effective Event Threat Detection custom modules for the
  /// given parent. This includes resident modules defined at the scope of the
  /// parent along with modules inherited from its ancestors.
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListEffectiveEventThreatDetectionCustomModules")
  public func listEffectiveEventThreatDetectionCustomModules(
    byItem: ListEffectiveEventThreatDetectionCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<EffectiveEventThreatDetectionCustomModule, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityCenterManagementV1
        .ListEffectiveEventThreatDetectionCustomModulesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listEffectiveEventThreatDetectionCustomModules(
        request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets the effective Event Threat Detection custom module at the given level.
  ///
  /// The difference between an
  /// [EffectiveEventThreatDetectionCustomModule][google.cloud.securitycentermanagement.v1.EffectiveEventThreatDetectionCustomModule]
  /// and an
  /// [EventThreatDetectionCustomModule][google.cloud.securitycentermanagement.v1.EventThreatDetectionCustomModule]
  /// is that the fields for an `EffectiveEventThreatDetectionCustomModule` are
  /// computed from ancestors if needed. For example, the enablement state for an
  /// `EventThreatDetectionCustomModule` can be `ENABLED`, `DISABLED`, or
  /// `INHERITED`. In contrast, the enablement state for an
  /// `EffectiveEventThreatDetectionCustomModule` is always computed as `ENABLED`
  /// or `DISABLED`.
  ///
  /// [google.cloud.securitycentermanagement.v1.EffectiveEventThreatDetectionCustomModule]: <doc:EffectiveEventThreatDetectionCustomModule>
  /// [google.cloud.securitycentermanagement.v1.EventThreatDetectionCustomModule]: <doc:EventThreatDetectionCustomModule>
  ///
  /// @Snippet(path: "SecurityCenterManagement_GetEffectiveEventThreatDetectionCustomModule")
  public func getEffectiveEventThreatDetectionCustomModule(
    request: GetEffectiveEventThreatDetectionCustomModuleRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EffectiveEventThreatDetectionCustomModule
  {
    try await self.inner.getEffectiveEventThreatDetectionCustomModule(
      request: request, options: options)
  }

  /// Lists all Event Threat Detection custom modules for the given organization,
  /// folder, or project. This includes resident modules defined at the scope of
  /// the parent along with modules inherited from ancestors.
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListEventThreatDetectionCustomModules")
  public func listEventThreatDetectionCustomModules(
    request: ListEventThreatDetectionCustomModulesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.ListEventThreatDetectionCustomModulesResponse
  {
    try await self.inner.listEventThreatDetectionCustomModules(request: request, options: options)
  }

  /// Lists all Event Threat Detection custom modules for the given organization,
  /// folder, or project. This includes resident modules defined at the scope of
  /// the parent along with modules inherited from ancestors.
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListEventThreatDetectionCustomModules")
  public func listEventThreatDetectionCustomModules(
    byItem: ListEventThreatDetectionCustomModulesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<EventThreatDetectionCustomModule, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityCenterManagementV1.ListEventThreatDetectionCustomModulesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listEventThreatDetectionCustomModules(
        request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists all resident Event Threat Detection custom modules for the given
  /// organization, folder, or project and its descendants.
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListDescendantEventThreatDetectionCustomModules")
  public func listDescendantEventThreatDetectionCustomModules(
    request: ListDescendantEventThreatDetectionCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.ListDescendantEventThreatDetectionCustomModulesResponse
  {
    try await self.inner.listDescendantEventThreatDetectionCustomModules(
      request: request, options: options)
  }

  /// Lists all resident Event Threat Detection custom modules for the given
  /// organization, folder, or project and its descendants.
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListDescendantEventThreatDetectionCustomModules")
  public func listDescendantEventThreatDetectionCustomModules(
    byItem: ListDescendantEventThreatDetectionCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<EventThreatDetectionCustomModule, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityCenterManagementV1
        .ListDescendantEventThreatDetectionCustomModulesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listDescendantEventThreatDetectionCustomModules(
        request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets an Event Threat Detection custom module.
  ///
  /// @Snippet(path: "SecurityCenterManagement_GetEventThreatDetectionCustomModule")
  public func getEventThreatDetectionCustomModule(
    request: GetEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
    try await self.inner.getEventThreatDetectionCustomModule(request: request, options: options)
  }

  /// Creates a resident Event Threat Detection custom module at the scope of the
  /// given organization, folder, or project, and creates inherited custom
  /// modules for all descendants of the given parent. These modules are enabled
  /// by default.
  ///
  /// @Snippet(path: "SecurityCenterManagement_CreateEventThreatDetectionCustomModule")
  public func createEventThreatDetectionCustomModule(
    request: CreateEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
    try await self.inner.createEventThreatDetectionCustomModule(request: request, options: options)
  }

  /// Updates the Event Threat Detection custom module with the given name based
  /// on the given update mask. Updating the enablement state is supported for
  /// both resident and inherited modules (though resident modules cannot have an
  /// enablement state of "inherited"). Updating the display name or
  /// configuration of a module is supported for resident modules only. The type
  /// of a module cannot be changed.
  ///
  /// @Snippet(path: "SecurityCenterManagement_UpdateEventThreatDetectionCustomModule")
  public func updateEventThreatDetectionCustomModule(
    request: UpdateEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
    try await self.inner.updateEventThreatDetectionCustomModule(request: request, options: options)
  }

  /// Deletes the specified Event Threat Detection custom module and all of its
  /// descendants in the resource hierarchy. This method is only supported for
  /// resident custom modules.
  ///
  /// @Snippet(path: "SecurityCenterManagement_DeleteEventThreatDetectionCustomModule")
  public func deleteEventThreatDetectionCustomModule(
    request: DeleteEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteEventThreatDetectionCustomModule(request: request, options: options)
  }

  /// Validates the given Event Threat Detection custom module.
  ///
  /// @Snippet(path: "SecurityCenterManagement_ValidateEventThreatDetectionCustomModule")
  public func validateEventThreatDetectionCustomModule(
    request: ValidateEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.ValidateEventThreatDetectionCustomModuleResponse
  {
    try await self.inner.validateEventThreatDetectionCustomModule(
      request: request, options: options)
  }

  /// Gets service settings for the specified Security Command Center service.
  ///
  /// @Snippet(path: "SecurityCenterManagement_GetSecurityCenterService")
  public func getSecurityCenterService(
    request: GetSecurityCenterServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService {
    try await self.inner.getSecurityCenterService(request: request, options: options)
  }

  /// Returns a list of all Security Command Center services for the given
  /// parent.
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListSecurityCenterServices")
  public func listSecurityCenterServices(
    request: ListSecurityCenterServicesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.ListSecurityCenterServicesResponse {
    try await self.inner.listSecurityCenterServices(request: request, options: options)
  }

  /// Returns a list of all Security Command Center services for the given
  /// parent.
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListSecurityCenterServices")
  public func listSecurityCenterServices(
    byItem: ListSecurityCenterServicesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SecurityCenterService, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityCenterManagementV1.ListSecurityCenterServicesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listSecurityCenterServices(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Updates a Security Command Center service using the given update mask.
  ///
  /// @Snippet(path: "SecurityCenterManagement_UpdateSecurityCenterService")
  public func updateSecurityCenterService(
    request: UpdateSecurityCenterServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService {
    try await self.inner.updateSecurityCenterService(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "SecurityCenterManagement_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "SecurityCenterManagement_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `SecurityCenterManagementClient`.
  ///
  /// To mock `SecurityCenterManagementClient` change your functions to receive
  /// `some SecurityCenterManagementProtocol` or `any SecurityCenterManagementProtocol`
  /// and pass a mock implementation in your tests.
  public protocol SecurityCenterManagementProtocol {
    /// See `SecurityCenterManagementClient.listEffectiveSecurityHealthAnalyticsCustomModules`.
    func listEffectiveSecurityHealthAnalyticsCustomModules(
      request: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListEffectiveSecurityHealthAnalyticsCustomModulesResponse

    /// See `SecurityCenterManagementClient.listEffectiveSecurityHealthAnalyticsCustomModules`.
    func listEffectiveSecurityHealthAnalyticsCustomModules(
      byItem: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest
    ) throws -> any AsyncSequence<EffectiveSecurityHealthAnalyticsCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.listEffectiveSecurityHealthAnalyticsCustomModules`.
    func listEffectiveSecurityHealthAnalyticsCustomModules(
      parent: Swift.String,
    ) throws -> any AsyncSequence<EffectiveSecurityHealthAnalyticsCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.getEffectiveSecurityHealthAnalyticsCustomModule`.
    func getEffectiveSecurityHealthAnalyticsCustomModule(
      request: GetEffectiveSecurityHealthAnalyticsCustomModuleRequest
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.EffectiveSecurityHealthAnalyticsCustomModule

    /// See `SecurityCenterManagementClient.getEffectiveSecurityHealthAnalyticsCustomModule`.
    func getEffectiveSecurityHealthAnalyticsCustomModule(
      name: Swift.String,
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.EffectiveSecurityHealthAnalyticsCustomModule

    /// See `SecurityCenterManagementClient.listSecurityHealthAnalyticsCustomModules`.
    func listSecurityHealthAnalyticsCustomModules(
      request: ListSecurityHealthAnalyticsCustomModulesRequest
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ListSecurityHealthAnalyticsCustomModulesResponse

    /// See `SecurityCenterManagementClient.listSecurityHealthAnalyticsCustomModules`.
    func listSecurityHealthAnalyticsCustomModules(
      byItem: ListSecurityHealthAnalyticsCustomModulesRequest
    ) throws -> any AsyncSequence<SecurityHealthAnalyticsCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.listSecurityHealthAnalyticsCustomModules`.
    func listSecurityHealthAnalyticsCustomModules(
      parent: Swift.String,
    ) throws -> any AsyncSequence<SecurityHealthAnalyticsCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.listDescendantSecurityHealthAnalyticsCustomModules`.
    func listDescendantSecurityHealthAnalyticsCustomModules(
      request: ListDescendantSecurityHealthAnalyticsCustomModulesRequest
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListDescendantSecurityHealthAnalyticsCustomModulesResponse

    /// See `SecurityCenterManagementClient.listDescendantSecurityHealthAnalyticsCustomModules`.
    func listDescendantSecurityHealthAnalyticsCustomModules(
      byItem: ListDescendantSecurityHealthAnalyticsCustomModulesRequest
    ) throws -> any AsyncSequence<SecurityHealthAnalyticsCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.listDescendantSecurityHealthAnalyticsCustomModules`.
    func listDescendantSecurityHealthAnalyticsCustomModules(
      parent: Swift.String,
    ) throws -> any AsyncSequence<SecurityHealthAnalyticsCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.getSecurityHealthAnalyticsCustomModule`.
    func getSecurityHealthAnalyticsCustomModule(
      request: GetSecurityHealthAnalyticsCustomModuleRequest
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule

    /// See `SecurityCenterManagementClient.getSecurityHealthAnalyticsCustomModule`.
    func getSecurityHealthAnalyticsCustomModule(
      name: Swift.String,
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule

    /// See `SecurityCenterManagementClient.createSecurityHealthAnalyticsCustomModule`.
    func createSecurityHealthAnalyticsCustomModule(
      request: CreateSecurityHealthAnalyticsCustomModuleRequest
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule

    /// See `SecurityCenterManagementClient.createSecurityHealthAnalyticsCustomModule`.
    func createSecurityHealthAnalyticsCustomModule(
      parent: Swift.String,
      securityHealthAnalyticsCustomModule: SecurityHealthAnalyticsCustomModule?,
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule

    /// See `SecurityCenterManagementClient.updateSecurityHealthAnalyticsCustomModule`.
    func updateSecurityHealthAnalyticsCustomModule(
      request: UpdateSecurityHealthAnalyticsCustomModuleRequest
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule

    /// See `SecurityCenterManagementClient.updateSecurityHealthAnalyticsCustomModule`.
    func updateSecurityHealthAnalyticsCustomModule(
      securityHealthAnalyticsCustomModule: SecurityHealthAnalyticsCustomModule?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule

    /// See `SecurityCenterManagementClient.deleteSecurityHealthAnalyticsCustomModule`.
    func deleteSecurityHealthAnalyticsCustomModule(
      request: DeleteSecurityHealthAnalyticsCustomModuleRequest) async throws

    /// See `SecurityCenterManagementClient.deleteSecurityHealthAnalyticsCustomModule`.
    func deleteSecurityHealthAnalyticsCustomModule(
      name: Swift.String,
    ) async throws

    /// See `SecurityCenterManagementClient.simulateSecurityHealthAnalyticsCustomModule`.
    func simulateSecurityHealthAnalyticsCustomModule(
      request: SimulateSecurityHealthAnalyticsCustomModuleRequest
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.SimulateSecurityHealthAnalyticsCustomModuleResponse

    /// See `SecurityCenterManagementClient.simulateSecurityHealthAnalyticsCustomModule`.
    func simulateSecurityHealthAnalyticsCustomModule(
      parent: Swift.String,
      customConfig: CustomConfig?,
      resource: SimulateSecurityHealthAnalyticsCustomModuleRequest.SimulatedResource?,
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.SimulateSecurityHealthAnalyticsCustomModuleResponse

    /// See `SecurityCenterManagementClient.listEffectiveEventThreatDetectionCustomModules`.
    func listEffectiveEventThreatDetectionCustomModules(
      request: ListEffectiveEventThreatDetectionCustomModulesRequest
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListEffectiveEventThreatDetectionCustomModulesResponse

    /// See `SecurityCenterManagementClient.listEffectiveEventThreatDetectionCustomModules`.
    func listEffectiveEventThreatDetectionCustomModules(
      byItem: ListEffectiveEventThreatDetectionCustomModulesRequest
    ) throws -> any AsyncSequence<EffectiveEventThreatDetectionCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.listEffectiveEventThreatDetectionCustomModules`.
    func listEffectiveEventThreatDetectionCustomModules(
      parent: Swift.String,
    ) throws -> any AsyncSequence<EffectiveEventThreatDetectionCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.getEffectiveEventThreatDetectionCustomModule`.
    func getEffectiveEventThreatDetectionCustomModule(
      request: GetEffectiveEventThreatDetectionCustomModuleRequest
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.EffectiveEventThreatDetectionCustomModule

    /// See `SecurityCenterManagementClient.getEffectiveEventThreatDetectionCustomModule`.
    func getEffectiveEventThreatDetectionCustomModule(
      name: Swift.String,
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.EffectiveEventThreatDetectionCustomModule

    /// See `SecurityCenterManagementClient.listEventThreatDetectionCustomModules`.
    func listEventThreatDetectionCustomModules(
      request: ListEventThreatDetectionCustomModulesRequest
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ListEventThreatDetectionCustomModulesResponse

    /// See `SecurityCenterManagementClient.listEventThreatDetectionCustomModules`.
    func listEventThreatDetectionCustomModules(
      byItem: ListEventThreatDetectionCustomModulesRequest
    ) throws -> any AsyncSequence<EventThreatDetectionCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.listEventThreatDetectionCustomModules`.
    func listEventThreatDetectionCustomModules(
      parent: Swift.String,
    ) throws -> any AsyncSequence<EventThreatDetectionCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.listDescendantEventThreatDetectionCustomModules`.
    func listDescendantEventThreatDetectionCustomModules(
      request: ListDescendantEventThreatDetectionCustomModulesRequest
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListDescendantEventThreatDetectionCustomModulesResponse

    /// See `SecurityCenterManagementClient.listDescendantEventThreatDetectionCustomModules`.
    func listDescendantEventThreatDetectionCustomModules(
      byItem: ListDescendantEventThreatDetectionCustomModulesRequest
    ) throws -> any AsyncSequence<EventThreatDetectionCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.listDescendantEventThreatDetectionCustomModules`.
    func listDescendantEventThreatDetectionCustomModules(
      parent: Swift.String,
    ) throws -> any AsyncSequence<EventThreatDetectionCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.getEventThreatDetectionCustomModule`.
    func getEventThreatDetectionCustomModule(request: GetEventThreatDetectionCustomModuleRequest)
      async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule

    /// See `SecurityCenterManagementClient.getEventThreatDetectionCustomModule`.
    func getEventThreatDetectionCustomModule(
      name: Swift.String,
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule

    /// See `SecurityCenterManagementClient.createEventThreatDetectionCustomModule`.
    func createEventThreatDetectionCustomModule(
      request: CreateEventThreatDetectionCustomModuleRequest
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule

    /// See `SecurityCenterManagementClient.createEventThreatDetectionCustomModule`.
    func createEventThreatDetectionCustomModule(
      parent: Swift.String,
      eventThreatDetectionCustomModule: EventThreatDetectionCustomModule?,
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule

    /// See `SecurityCenterManagementClient.updateEventThreatDetectionCustomModule`.
    func updateEventThreatDetectionCustomModule(
      request: UpdateEventThreatDetectionCustomModuleRequest
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule

    /// See `SecurityCenterManagementClient.updateEventThreatDetectionCustomModule`.
    func updateEventThreatDetectionCustomModule(
      eventThreatDetectionCustomModule: EventThreatDetectionCustomModule?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule

    /// See `SecurityCenterManagementClient.deleteEventThreatDetectionCustomModule`.
    func deleteEventThreatDetectionCustomModule(
      request: DeleteEventThreatDetectionCustomModuleRequest) async throws

    /// See `SecurityCenterManagementClient.deleteEventThreatDetectionCustomModule`.
    func deleteEventThreatDetectionCustomModule(
      name: Swift.String,
    ) async throws

    /// See `SecurityCenterManagementClient.validateEventThreatDetectionCustomModule`.
    func validateEventThreatDetectionCustomModule(
      request: ValidateEventThreatDetectionCustomModuleRequest
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ValidateEventThreatDetectionCustomModuleResponse

    /// See `SecurityCenterManagementClient.getSecurityCenterService`.
    func getSecurityCenterService(request: GetSecurityCenterServiceRequest) async throws
      -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService

    /// See `SecurityCenterManagementClient.getSecurityCenterService`.
    func getSecurityCenterService(
      name: Swift.String,
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService

    /// See `SecurityCenterManagementClient.listSecurityCenterServices`.
    func listSecurityCenterServices(request: ListSecurityCenterServicesRequest) async throws
      -> GoogleCloudSecurityCenterManagementV1.ListSecurityCenterServicesResponse

    /// See `SecurityCenterManagementClient.listSecurityCenterServices`.
    func listSecurityCenterServices(
      byItem: ListSecurityCenterServicesRequest
    ) throws -> any AsyncSequence<SecurityCenterService, Swift.Error>

    /// See `SecurityCenterManagementClient.listSecurityCenterServices`.
    func listSecurityCenterServices(
      parent: Swift.String,
    ) throws -> any AsyncSequence<SecurityCenterService, Swift.Error>

    /// See `SecurityCenterManagementClient.updateSecurityCenterService`.
    func updateSecurityCenterService(request: UpdateSecurityCenterServiceRequest) async throws
      -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService

    /// See `SecurityCenterManagementClient.updateSecurityCenterService`.
    func updateSecurityCenterService(
      securityCenterService: SecurityCenterService?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService

    /// See `SecurityCenterManagementClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `SecurityCenterManagementClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `SecurityCenterManagementClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `SecurityCenterManagementClient.listEffectiveSecurityHealthAnalyticsCustomModules`.
    func listEffectiveSecurityHealthAnalyticsCustomModules(
      request: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListEffectiveSecurityHealthAnalyticsCustomModulesResponse

    /// See `SecurityCenterManagementClient.listEffectiveSecurityHealthAnalyticsCustomModules`.
    func listEffectiveSecurityHealthAnalyticsCustomModules(
      byItem: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<EffectiveSecurityHealthAnalyticsCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.getEffectiveSecurityHealthAnalyticsCustomModule`.
    func getEffectiveSecurityHealthAnalyticsCustomModule(
      request: GetEffectiveSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.EffectiveSecurityHealthAnalyticsCustomModule

    /// See `SecurityCenterManagementClient.listSecurityHealthAnalyticsCustomModules`.
    func listSecurityHealthAnalyticsCustomModules(
      request: ListSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ListSecurityHealthAnalyticsCustomModulesResponse

    /// See `SecurityCenterManagementClient.listSecurityHealthAnalyticsCustomModules`.
    func listSecurityHealthAnalyticsCustomModules(
      byItem: ListSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<SecurityHealthAnalyticsCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.listDescendantSecurityHealthAnalyticsCustomModules`.
    func listDescendantSecurityHealthAnalyticsCustomModules(
      request: ListDescendantSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListDescendantSecurityHealthAnalyticsCustomModulesResponse

    /// See `SecurityCenterManagementClient.listDescendantSecurityHealthAnalyticsCustomModules`.
    func listDescendantSecurityHealthAnalyticsCustomModules(
      byItem: ListDescendantSecurityHealthAnalyticsCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<SecurityHealthAnalyticsCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.getSecurityHealthAnalyticsCustomModule`.
    func getSecurityHealthAnalyticsCustomModule(
      request: GetSecurityHealthAnalyticsCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule

    /// See `SecurityCenterManagementClient.createSecurityHealthAnalyticsCustomModule`.
    func createSecurityHealthAnalyticsCustomModule(
      request: CreateSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule

    /// See `SecurityCenterManagementClient.updateSecurityHealthAnalyticsCustomModule`.
    func updateSecurityHealthAnalyticsCustomModule(
      request: UpdateSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule

    /// See `SecurityCenterManagementClient.deleteSecurityHealthAnalyticsCustomModule`.
    func deleteSecurityHealthAnalyticsCustomModule(
      request: DeleteSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `SecurityCenterManagementClient.simulateSecurityHealthAnalyticsCustomModule`.
    func simulateSecurityHealthAnalyticsCustomModule(
      request: SimulateSecurityHealthAnalyticsCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.SimulateSecurityHealthAnalyticsCustomModuleResponse

    /// See `SecurityCenterManagementClient.listEffectiveEventThreatDetectionCustomModules`.
    func listEffectiveEventThreatDetectionCustomModules(
      request: ListEffectiveEventThreatDetectionCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListEffectiveEventThreatDetectionCustomModulesResponse

    /// See `SecurityCenterManagementClient.listEffectiveEventThreatDetectionCustomModules`.
    func listEffectiveEventThreatDetectionCustomModules(
      byItem: ListEffectiveEventThreatDetectionCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<EffectiveEventThreatDetectionCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.getEffectiveEventThreatDetectionCustomModule`.
    func getEffectiveEventThreatDetectionCustomModule(
      request: GetEffectiveEventThreatDetectionCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.EffectiveEventThreatDetectionCustomModule

    /// See `SecurityCenterManagementClient.listEventThreatDetectionCustomModules`.
    func listEventThreatDetectionCustomModules(
      request: ListEventThreatDetectionCustomModulesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ListEventThreatDetectionCustomModulesResponse

    /// See `SecurityCenterManagementClient.listEventThreatDetectionCustomModules`.
    func listEventThreatDetectionCustomModules(
      byItem: ListEventThreatDetectionCustomModulesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<EventThreatDetectionCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.listDescendantEventThreatDetectionCustomModules`.
    func listDescendantEventThreatDetectionCustomModules(
      request: ListDescendantEventThreatDetectionCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1
      .ListDescendantEventThreatDetectionCustomModulesResponse

    /// See `SecurityCenterManagementClient.listDescendantEventThreatDetectionCustomModules`.
    func listDescendantEventThreatDetectionCustomModules(
      byItem: ListDescendantEventThreatDetectionCustomModulesRequest,
      options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<EventThreatDetectionCustomModule, Swift.Error>

    /// See `SecurityCenterManagementClient.getEventThreatDetectionCustomModule`.
    func getEventThreatDetectionCustomModule(
      request: GetEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule

    /// See `SecurityCenterManagementClient.createEventThreatDetectionCustomModule`.
    func createEventThreatDetectionCustomModule(
      request: CreateEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule

    /// See `SecurityCenterManagementClient.updateEventThreatDetectionCustomModule`.
    func updateEventThreatDetectionCustomModule(
      request: UpdateEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule

    /// See `SecurityCenterManagementClient.deleteEventThreatDetectionCustomModule`.
    func deleteEventThreatDetectionCustomModule(
      request: DeleteEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `SecurityCenterManagementClient.validateEventThreatDetectionCustomModule`.
    func validateEventThreatDetectionCustomModule(
      request: ValidateEventThreatDetectionCustomModuleRequest,
      options: GoogleCloudGax.RequestOptions
    ) async throws
      -> GoogleCloudSecurityCenterManagementV1.ValidateEventThreatDetectionCustomModuleResponse

    /// See `SecurityCenterManagementClient.getSecurityCenterService`.
    func getSecurityCenterService(
      request: GetSecurityCenterServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService

    /// See `SecurityCenterManagementClient.listSecurityCenterServices`.
    func listSecurityCenterServices(
      request: ListSecurityCenterServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.ListSecurityCenterServicesResponse

    /// See `SecurityCenterManagementClient.listSecurityCenterServices`.
    func listSecurityCenterServices(
      byItem: ListSecurityCenterServicesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<SecurityCenterService, Swift.Error>

    /// See `SecurityCenterManagementClient.updateSecurityCenterService`.
    func updateSecurityCenterService(
      request: UpdateSecurityCenterServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService

    /// See `SecurityCenterManagementClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `SecurityCenterManagementClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `SecurityCenterManagementClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}

// Default implementations
extension Clients.SecurityCenterManagementProtocol {
  public func listEffectiveSecurityHealthAnalyticsCustomModules(
    request: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1
    .ListEffectiveSecurityHealthAnalyticsCustomModulesResponse
  {
    try await self.listEffectiveSecurityHealthAnalyticsCustomModules(
      request: request, options: .init())
  }

  public func listEffectiveSecurityHealthAnalyticsCustomModules(
    request: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1
    .ListEffectiveSecurityHealthAnalyticsCustomModulesResponse
  {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listEffectiveSecurityHealthAnalyticsCustomModules(
    byItem: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest
  ) throws -> any AsyncSequence<EffectiveSecurityHealthAnalyticsCustomModule, Swift.Error> {
    try self.listEffectiveSecurityHealthAnalyticsCustomModules(byItem: byItem, options: .init())
  }

  public func listEffectiveSecurityHealthAnalyticsCustomModules(
    byItem: ListEffectiveSecurityHealthAnalyticsCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<EffectiveSecurityHealthAnalyticsCustomModule, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityCenterManagementV1
        .ListEffectiveSecurityHealthAnalyticsCustomModulesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listEffectiveSecurityHealthAnalyticsCustomModules(
    parent: Swift.String,
  ) throws -> any AsyncSequence<EffectiveSecurityHealthAnalyticsCustomModule, Swift.Error> {
    let request = ListEffectiveSecurityHealthAnalyticsCustomModulesRequest().with {
      $0.parent = parent
    }
    return try self.listEffectiveSecurityHealthAnalyticsCustomModules(byItem: request)
  }

  public func getEffectiveSecurityHealthAnalyticsCustomModule(
    request: GetEffectiveSecurityHealthAnalyticsCustomModuleRequest
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.EffectiveSecurityHealthAnalyticsCustomModule
  {
    try await self.getEffectiveSecurityHealthAnalyticsCustomModule(
      request: request, options: .init())
  }

  public func getEffectiveSecurityHealthAnalyticsCustomModule(
    request: GetEffectiveSecurityHealthAnalyticsCustomModuleRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.EffectiveSecurityHealthAnalyticsCustomModule
  {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getEffectiveSecurityHealthAnalyticsCustomModule(
    name: Swift.String,
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.EffectiveSecurityHealthAnalyticsCustomModule
  {
    let request = GetEffectiveSecurityHealthAnalyticsCustomModuleRequest().with {
      $0.name = name
    }
    return try await self.getEffectiveSecurityHealthAnalyticsCustomModule(request: request)
  }

  public func listSecurityHealthAnalyticsCustomModules(
    request: ListSecurityHealthAnalyticsCustomModulesRequest
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.ListSecurityHealthAnalyticsCustomModulesResponse
  {
    try await self.listSecurityHealthAnalyticsCustomModules(request: request, options: .init())
  }

  public func listSecurityHealthAnalyticsCustomModules(
    request: ListSecurityHealthAnalyticsCustomModulesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.ListSecurityHealthAnalyticsCustomModulesResponse
  {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSecurityHealthAnalyticsCustomModules(
    byItem: ListSecurityHealthAnalyticsCustomModulesRequest
  ) throws -> any AsyncSequence<SecurityHealthAnalyticsCustomModule, Swift.Error> {
    try self.listSecurityHealthAnalyticsCustomModules(byItem: byItem, options: .init())
  }

  public func listSecurityHealthAnalyticsCustomModules(
    byItem: ListSecurityHealthAnalyticsCustomModulesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SecurityHealthAnalyticsCustomModule, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityCenterManagementV1.ListSecurityHealthAnalyticsCustomModulesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listSecurityHealthAnalyticsCustomModules(
    parent: Swift.String,
  ) throws -> any AsyncSequence<SecurityHealthAnalyticsCustomModule, Swift.Error> {
    let request = ListSecurityHealthAnalyticsCustomModulesRequest().with {
      $0.parent = parent
    }
    return try self.listSecurityHealthAnalyticsCustomModules(byItem: request)
  }

  public func listDescendantSecurityHealthAnalyticsCustomModules(
    request: ListDescendantSecurityHealthAnalyticsCustomModulesRequest
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1
    .ListDescendantSecurityHealthAnalyticsCustomModulesResponse
  {
    try await self.listDescendantSecurityHealthAnalyticsCustomModules(
      request: request, options: .init())
  }

  public func listDescendantSecurityHealthAnalyticsCustomModules(
    request: ListDescendantSecurityHealthAnalyticsCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1
    .ListDescendantSecurityHealthAnalyticsCustomModulesResponse
  {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listDescendantSecurityHealthAnalyticsCustomModules(
    byItem: ListDescendantSecurityHealthAnalyticsCustomModulesRequest
  ) throws -> any AsyncSequence<SecurityHealthAnalyticsCustomModule, Swift.Error> {
    try self.listDescendantSecurityHealthAnalyticsCustomModules(byItem: byItem, options: .init())
  }

  public func listDescendantSecurityHealthAnalyticsCustomModules(
    byItem: ListDescendantSecurityHealthAnalyticsCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SecurityHealthAnalyticsCustomModule, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityCenterManagementV1
        .ListDescendantSecurityHealthAnalyticsCustomModulesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDescendantSecurityHealthAnalyticsCustomModules(
    parent: Swift.String,
  ) throws -> any AsyncSequence<SecurityHealthAnalyticsCustomModule, Swift.Error> {
    let request = ListDescendantSecurityHealthAnalyticsCustomModulesRequest().with {
      $0.parent = parent
    }
    return try self.listDescendantSecurityHealthAnalyticsCustomModules(byItem: request)
  }

  public func getSecurityHealthAnalyticsCustomModule(
    request: GetSecurityHealthAnalyticsCustomModuleRequest
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
    try await self.getSecurityHealthAnalyticsCustomModule(request: request, options: .init())
  }

  public func getSecurityHealthAnalyticsCustomModule(
    request: GetSecurityHealthAnalyticsCustomModuleRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSecurityHealthAnalyticsCustomModule(
    name: Swift.String,
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
    let request = GetSecurityHealthAnalyticsCustomModuleRequest().with {
      $0.name = name
    }
    return try await self.getSecurityHealthAnalyticsCustomModule(request: request)
  }

  public func createSecurityHealthAnalyticsCustomModule(
    request: CreateSecurityHealthAnalyticsCustomModuleRequest
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
    try await self.createSecurityHealthAnalyticsCustomModule(request: request, options: .init())
  }

  public func createSecurityHealthAnalyticsCustomModule(
    request: CreateSecurityHealthAnalyticsCustomModuleRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createSecurityHealthAnalyticsCustomModule(
    parent: Swift.String,
    securityHealthAnalyticsCustomModule: SecurityHealthAnalyticsCustomModule?,
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
    let request = CreateSecurityHealthAnalyticsCustomModuleRequest().with {
      $0.parent = parent
      $0.securityHealthAnalyticsCustomModule = securityHealthAnalyticsCustomModule
    }
    return try await self.createSecurityHealthAnalyticsCustomModule(request: request)
  }

  public func updateSecurityHealthAnalyticsCustomModule(
    request: UpdateSecurityHealthAnalyticsCustomModuleRequest
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
    try await self.updateSecurityHealthAnalyticsCustomModule(request: request, options: .init())
  }

  public func updateSecurityHealthAnalyticsCustomModule(
    request: UpdateSecurityHealthAnalyticsCustomModuleRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateSecurityHealthAnalyticsCustomModule(
    securityHealthAnalyticsCustomModule: SecurityHealthAnalyticsCustomModule?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityHealthAnalyticsCustomModule {
    let request = UpdateSecurityHealthAnalyticsCustomModuleRequest().with {
      $0.securityHealthAnalyticsCustomModule = securityHealthAnalyticsCustomModule
      $0.updateMask = updateMask
    }
    return try await self.updateSecurityHealthAnalyticsCustomModule(request: request)
  }

  public func deleteSecurityHealthAnalyticsCustomModule(
    request: DeleteSecurityHealthAnalyticsCustomModuleRequest
  ) async throws {
    try await self.deleteSecurityHealthAnalyticsCustomModule(request: request, options: .init())
  }

  public func deleteSecurityHealthAnalyticsCustomModule(
    request: DeleteSecurityHealthAnalyticsCustomModuleRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteSecurityHealthAnalyticsCustomModule(
    name: Swift.String,
  ) async throws {
    let request = DeleteSecurityHealthAnalyticsCustomModuleRequest().with {
      $0.name = name
    }
    try await self.deleteSecurityHealthAnalyticsCustomModule(request: request)
  }

  public func simulateSecurityHealthAnalyticsCustomModule(
    request: SimulateSecurityHealthAnalyticsCustomModuleRequest
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.SimulateSecurityHealthAnalyticsCustomModuleResponse
  {
    try await self.simulateSecurityHealthAnalyticsCustomModule(request: request, options: .init())
  }

  public func simulateSecurityHealthAnalyticsCustomModule(
    request: SimulateSecurityHealthAnalyticsCustomModuleRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.SimulateSecurityHealthAnalyticsCustomModuleResponse
  {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func simulateSecurityHealthAnalyticsCustomModule(
    parent: Swift.String,
    customConfig: CustomConfig?,
    resource: SimulateSecurityHealthAnalyticsCustomModuleRequest.SimulatedResource?,
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.SimulateSecurityHealthAnalyticsCustomModuleResponse
  {
    let request = SimulateSecurityHealthAnalyticsCustomModuleRequest().with {
      $0.parent = parent
      $0.customConfig = customConfig
      $0.resource = resource
    }
    return try await self.simulateSecurityHealthAnalyticsCustomModule(request: request)
  }

  public func listEffectiveEventThreatDetectionCustomModules(
    request: ListEffectiveEventThreatDetectionCustomModulesRequest
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.ListEffectiveEventThreatDetectionCustomModulesResponse
  {
    try await self.listEffectiveEventThreatDetectionCustomModules(
      request: request, options: .init())
  }

  public func listEffectiveEventThreatDetectionCustomModules(
    request: ListEffectiveEventThreatDetectionCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.ListEffectiveEventThreatDetectionCustomModulesResponse
  {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listEffectiveEventThreatDetectionCustomModules(
    byItem: ListEffectiveEventThreatDetectionCustomModulesRequest
  ) throws -> any AsyncSequence<EffectiveEventThreatDetectionCustomModule, Swift.Error> {
    try self.listEffectiveEventThreatDetectionCustomModules(byItem: byItem, options: .init())
  }

  public func listEffectiveEventThreatDetectionCustomModules(
    byItem: ListEffectiveEventThreatDetectionCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<EffectiveEventThreatDetectionCustomModule, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityCenterManagementV1
        .ListEffectiveEventThreatDetectionCustomModulesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listEffectiveEventThreatDetectionCustomModules(
    parent: Swift.String,
  ) throws -> any AsyncSequence<EffectiveEventThreatDetectionCustomModule, Swift.Error> {
    let request = ListEffectiveEventThreatDetectionCustomModulesRequest().with {
      $0.parent = parent
    }
    return try self.listEffectiveEventThreatDetectionCustomModules(byItem: request)
  }

  public func getEffectiveEventThreatDetectionCustomModule(
    request: GetEffectiveEventThreatDetectionCustomModuleRequest
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EffectiveEventThreatDetectionCustomModule
  {
    try await self.getEffectiveEventThreatDetectionCustomModule(request: request, options: .init())
  }

  public func getEffectiveEventThreatDetectionCustomModule(
    request: GetEffectiveEventThreatDetectionCustomModuleRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EffectiveEventThreatDetectionCustomModule
  {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getEffectiveEventThreatDetectionCustomModule(
    name: Swift.String,
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EffectiveEventThreatDetectionCustomModule
  {
    let request = GetEffectiveEventThreatDetectionCustomModuleRequest().with {
      $0.name = name
    }
    return try await self.getEffectiveEventThreatDetectionCustomModule(request: request)
  }

  public func listEventThreatDetectionCustomModules(
    request: ListEventThreatDetectionCustomModulesRequest
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.ListEventThreatDetectionCustomModulesResponse
  {
    try await self.listEventThreatDetectionCustomModules(request: request, options: .init())
  }

  public func listEventThreatDetectionCustomModules(
    request: ListEventThreatDetectionCustomModulesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.ListEventThreatDetectionCustomModulesResponse
  {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listEventThreatDetectionCustomModules(
    byItem: ListEventThreatDetectionCustomModulesRequest
  ) throws -> any AsyncSequence<EventThreatDetectionCustomModule, Swift.Error> {
    try self.listEventThreatDetectionCustomModules(byItem: byItem, options: .init())
  }

  public func listEventThreatDetectionCustomModules(
    byItem: ListEventThreatDetectionCustomModulesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<EventThreatDetectionCustomModule, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityCenterManagementV1.ListEventThreatDetectionCustomModulesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listEventThreatDetectionCustomModules(
    parent: Swift.String,
  ) throws -> any AsyncSequence<EventThreatDetectionCustomModule, Swift.Error> {
    let request = ListEventThreatDetectionCustomModulesRequest().with {
      $0.parent = parent
    }
    return try self.listEventThreatDetectionCustomModules(byItem: request)
  }

  public func listDescendantEventThreatDetectionCustomModules(
    request: ListDescendantEventThreatDetectionCustomModulesRequest
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.ListDescendantEventThreatDetectionCustomModulesResponse
  {
    try await self.listDescendantEventThreatDetectionCustomModules(
      request: request, options: .init())
  }

  public func listDescendantEventThreatDetectionCustomModules(
    request: ListDescendantEventThreatDetectionCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.ListDescendantEventThreatDetectionCustomModulesResponse
  {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listDescendantEventThreatDetectionCustomModules(
    byItem: ListDescendantEventThreatDetectionCustomModulesRequest
  ) throws -> any AsyncSequence<EventThreatDetectionCustomModule, Swift.Error> {
    try self.listDescendantEventThreatDetectionCustomModules(byItem: byItem, options: .init())
  }

  public func listDescendantEventThreatDetectionCustomModules(
    byItem: ListDescendantEventThreatDetectionCustomModulesRequest,
    options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<EventThreatDetectionCustomModule, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityCenterManagementV1
        .ListDescendantEventThreatDetectionCustomModulesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDescendantEventThreatDetectionCustomModules(
    parent: Swift.String,
  ) throws -> any AsyncSequence<EventThreatDetectionCustomModule, Swift.Error> {
    let request = ListDescendantEventThreatDetectionCustomModulesRequest().with {
      $0.parent = parent
    }
    return try self.listDescendantEventThreatDetectionCustomModules(byItem: request)
  }

  public func getEventThreatDetectionCustomModule(
    request: GetEventThreatDetectionCustomModuleRequest
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
    try await self.getEventThreatDetectionCustomModule(request: request, options: .init())
  }

  public func getEventThreatDetectionCustomModule(
    request: GetEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getEventThreatDetectionCustomModule(
    name: Swift.String,
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
    let request = GetEventThreatDetectionCustomModuleRequest().with {
      $0.name = name
    }
    return try await self.getEventThreatDetectionCustomModule(request: request)
  }

  public func createEventThreatDetectionCustomModule(
    request: CreateEventThreatDetectionCustomModuleRequest
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
    try await self.createEventThreatDetectionCustomModule(request: request, options: .init())
  }

  public func createEventThreatDetectionCustomModule(
    request: CreateEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createEventThreatDetectionCustomModule(
    parent: Swift.String,
    eventThreatDetectionCustomModule: EventThreatDetectionCustomModule?,
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
    let request = CreateEventThreatDetectionCustomModuleRequest().with {
      $0.parent = parent
      $0.eventThreatDetectionCustomModule = eventThreatDetectionCustomModule
    }
    return try await self.createEventThreatDetectionCustomModule(request: request)
  }

  public func updateEventThreatDetectionCustomModule(
    request: UpdateEventThreatDetectionCustomModuleRequest
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
    try await self.updateEventThreatDetectionCustomModule(request: request, options: .init())
  }

  public func updateEventThreatDetectionCustomModule(
    request: UpdateEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateEventThreatDetectionCustomModule(
    eventThreatDetectionCustomModule: EventThreatDetectionCustomModule?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudSecurityCenterManagementV1.EventThreatDetectionCustomModule {
    let request = UpdateEventThreatDetectionCustomModuleRequest().with {
      $0.eventThreatDetectionCustomModule = eventThreatDetectionCustomModule
      $0.updateMask = updateMask
    }
    return try await self.updateEventThreatDetectionCustomModule(request: request)
  }

  public func deleteEventThreatDetectionCustomModule(
    request: DeleteEventThreatDetectionCustomModuleRequest
  ) async throws {
    try await self.deleteEventThreatDetectionCustomModule(request: request, options: .init())
  }

  public func deleteEventThreatDetectionCustomModule(
    request: DeleteEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteEventThreatDetectionCustomModule(
    name: Swift.String,
  ) async throws {
    let request = DeleteEventThreatDetectionCustomModuleRequest().with {
      $0.name = name
    }
    try await self.deleteEventThreatDetectionCustomModule(request: request)
  }

  public func validateEventThreatDetectionCustomModule(
    request: ValidateEventThreatDetectionCustomModuleRequest
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.ValidateEventThreatDetectionCustomModuleResponse
  {
    try await self.validateEventThreatDetectionCustomModule(request: request, options: .init())
  }

  public func validateEventThreatDetectionCustomModule(
    request: ValidateEventThreatDetectionCustomModuleRequest, options: GoogleCloudGax.RequestOptions
  ) async throws
    -> GoogleCloudSecurityCenterManagementV1.ValidateEventThreatDetectionCustomModuleResponse
  {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSecurityCenterService(request: GetSecurityCenterServiceRequest) async throws
    -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService
  {
    try await self.getSecurityCenterService(request: request, options: .init())
  }

  public func getSecurityCenterService(
    request: GetSecurityCenterServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSecurityCenterService(
    name: Swift.String,
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService {
    let request = GetSecurityCenterServiceRequest().with {
      $0.name = name
    }
    return try await self.getSecurityCenterService(request: request)
  }

  public func listSecurityCenterServices(request: ListSecurityCenterServicesRequest) async throws
    -> GoogleCloudSecurityCenterManagementV1.ListSecurityCenterServicesResponse
  {
    try await self.listSecurityCenterServices(request: request, options: .init())
  }

  public func listSecurityCenterServices(
    request: ListSecurityCenterServicesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.ListSecurityCenterServicesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSecurityCenterServices(
    byItem: ListSecurityCenterServicesRequest
  ) throws -> any AsyncSequence<SecurityCenterService, Swift.Error> {
    try self.listSecurityCenterServices(byItem: byItem, options: .init())
  }

  public func listSecurityCenterServices(
    byItem: ListSecurityCenterServicesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SecurityCenterService, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudSecurityCenterManagementV1.ListSecurityCenterServicesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listSecurityCenterServices(
    parent: Swift.String,
  ) throws -> any AsyncSequence<SecurityCenterService, Swift.Error> {
    let request = ListSecurityCenterServicesRequest().with {
      $0.parent = parent
    }
    return try self.listSecurityCenterServices(byItem: request)
  }

  public func updateSecurityCenterService(request: UpdateSecurityCenterServiceRequest) async throws
    -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService
  {
    try await self.updateSecurityCenterService(request: request, options: .init())
  }

  public func updateSecurityCenterService(
    request: UpdateSecurityCenterServiceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateSecurityCenterService(
    securityCenterService: SecurityCenterService?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudSecurityCenterManagementV1.SecurityCenterService {
    let request = UpdateSecurityCenterServiceRequest().with {
      $0.securityCenterService = securityCenterService
      $0.updateMask = updateMask
    }
    return try await self.updateSecurityCenterService(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
