// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// Response message for
/// [SecurityCenterManagement.SimulateSecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.SecurityCenterManagement.SimulateSecurityHealthAnalyticsCustomModule].
///
/// [google.cloud.securitycentermanagement.v1.SecurityCenterManagement.SimulateSecurityHealthAnalyticsCustomModule]: <doc:SecurityCenterManagementClient/simulateSecurityHealthAnalyticsCustomModule(request:options:)>
public struct SimulateSecurityHealthAnalyticsCustomModuleResponse: Codable, Equatable,
  GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Result for test case in the corresponding request.
  public var result: SimulateSecurityHealthAnalyticsCustomModuleResponse.SimulatedResult? = nil

  /// Initialize a new instance of `SimulateSecurityHealthAnalyticsCustomModuleResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SimulateSecurityHealthAnalyticsCustomModuleResponse().with { $0.result = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Possible test result.
  public struct SimulatedResult: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The result of the simulation.
    public var result: OneOf_Result? = nil

    /// Initialize a new instance of `SimulatedResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SimulatedResult().with { $0.finding = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case finding = "finding"
      case noViolation = "noViolation"
      case error = "error"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var result: OneOf_Result? = nil
      let resultCheckAndSet = {
        if result != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'result'"))
        }
        result = $0
      }
      if let finding = try container.decodeIfPresent(SimulatedFinding?.self, forKey: .finding) {
        try resultCheckAndSet(.finding(finding))
      }
      if let noViolation = try container.decodeIfPresent(
        GoogleCloudWKT.Empty?.self, forKey: .noViolation)
      {
        try resultCheckAndSet(.noViolation(noViolation))
      }
      if let error = try container.decodeIfPresent(GoogleRpc.Status?.self, forKey: .error) {
        try resultCheckAndSet(.error(error))
      }
      self.result = result
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.result {
        switch choice {
        case .finding(let value):
          try container.encode(value, forKey: .finding)
        case .noViolation(let value):
          try container.encode(value, forKey: .noViolation)
        case .error(let value):
          try container.encode(value, forKey: .error)
        }
      }
    }

    /// The result of the simulation.
    public enum OneOf_Result: Codable, Equatable, Sendable {
      /// Finding that would be published for the test case if a violation is
      /// detected.
      indirect case finding(SimulatedFinding?)
      /// Indicates that the test case does not trigger any violation.
      indirect case noViolation(GoogleCloudWKT.Empty?)
      /// Error encountered during the test.
      indirect case error(GoogleRpc.Status?)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.securitycentermanagement.v1.SimulateSecurityHealthAnalyticsCustomModuleResponse.SimulatedResult"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.securitycentermanagement.v1.SimulateSecurityHealthAnalyticsCustomModuleResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
