// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleIAMV1

/// Request message for
/// [SecurityCenterManagement.SimulateSecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.SecurityCenterManagement.SimulateSecurityHealthAnalyticsCustomModule].
/// The maximum size of the request is 4 MiB.
///
/// [google.cloud.securitycentermanagement.v1.SecurityCenterManagement.SimulateSecurityHealthAnalyticsCustomModule]: <doc:SecurityCenterManagementClient/simulateSecurityHealthAnalyticsCustomModule(request:)>
public struct SimulateSecurityHealthAnalyticsCustomModuleRequest: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// Required. The relative resource name of the organization, project, or
  /// folder. For more information about relative resource names, see [AIP-122:
  /// Resource names](https://google.aip.dev/122). Example:
  /// `organizations/{organization_id}`.
  public var parent: Swift.String = Swift.String()

  /// Required. The custom configuration that you need to test.
  public var customConfig: CustomConfig? = nil

  /// Required. Resource data to simulate custom module against.
  public var resource: SimulateSecurityHealthAnalyticsCustomModuleRequest.SimulatedResource? = nil

  /// Initialize a new instance of `SimulateSecurityHealthAnalyticsCustomModuleRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SimulateSecurityHealthAnalyticsCustomModuleRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Manually constructed information about a resource.
  public struct SimulatedResource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The type of the resource. For example,
    /// `compute.googleapis.com/Disk`.
    public var resourceType: Swift.String = Swift.String()

    /// Optional. A representation of the Google Cloud resource. Should match the
    /// Google Cloud resource JSON format.
    ///
    /// If the custom module evaluates only the IAM allow policy, then you can
    /// omit this field.
    public var resourceData: GoogleCloudWkt.Struct? = nil

    /// Optional. A representation of the IAM allow policy.
    ///
    /// If the custom module evaluates only the resource data, then you can omit
    /// this field.
    public var iamPolicyData: GoogleIAMV1.Policy? = nil

    /// Initialize a new instance of `SimulatedResource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SimulatedResource().with { $0.resourceType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.securitycentermanagement.v1.SimulateSecurityHealthAnalyticsCustomModuleRequest.SimulatedResource"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.securitycentermanagement.v1.SimulateSecurityHealthAnalyticsCustomModuleRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
