// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleIAMV1

/// Request message for
/// [SecurityCenterManagement.SimulateSecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.SecurityCenterManagement.SimulateSecurityHealthAnalyticsCustomModule].
/// The maximum size of the request is 4 MiB.
///
/// [google.cloud.securitycentermanagement.v1.SecurityCenterManagement.SimulateSecurityHealthAnalyticsCustomModule]: <doc:SecurityCenterManagementClient/simulateSecurityHealthAnalyticsCustomModule(request:options:)>
public struct SimulateSecurityHealthAnalyticsCustomModuleRequest: Codable, Equatable, GoogleCloudWKT
    ._AnyPackable,
  Sendable
{
  /// Required. The relative resource name of the organization, project, or
  /// folder. For more information about relative resource names, see [AIP-122:
  /// Resource names](https://google.aip.dev/122). Example:
  /// `organizations/{organization_id}`.
  public var parent: Swift.String = Swift.String()

  /// Required. The custom configuration that you need to test.
  public var customConfig: CustomConfig? = nil

  /// Required. Resource data to simulate custom module against.
  public var resource: SimulateSecurityHealthAnalyticsCustomModuleRequest.SimulatedResource? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `SimulateSecurityHealthAnalyticsCustomModuleRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SimulateSecurityHealthAnalyticsCustomModuleRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let customConfig = CodingKeys(stringValue: "customConfig")
    static let resource = CodingKeys(stringValue: "resource")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "customConfig",
      "resource",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.customConfig = try container.decodeIfPresent(CustomConfig.self, forKey: .customConfig)
    self.resource = try container.decodeIfPresent(
      SimulateSecurityHealthAnalyticsCustomModuleRequest.SimulatedResource.self, forKey: .resource)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.customConfig, forKey: .customConfig)
    try container.encodeIfPresent(self.resource, forKey: .resource)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Manually constructed information about a resource.
  public struct SimulatedResource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The type of the resource. For example,
    /// `compute.googleapis.com/Disk`.
    public var resourceType: Swift.String = Swift.String()

    /// Optional. A representation of the Google Cloud resource. Should match the
    /// Google Cloud resource JSON format.
    ///
    /// If the custom module evaluates only the IAM allow policy, then you can
    /// omit this field.
    public var resourceData: GoogleCloudWKT.Struct? = nil

    /// Optional. A representation of the IAM allow policy.
    ///
    /// If the custom module evaluates only the resource data, then you can omit
    /// this field.
    public var iamPolicyData: GoogleIAMV1.Policy? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `SimulatedResource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SimulatedResource().with { $0.resourceType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let resourceType = CodingKeys(stringValue: "resourceType")
      static let resourceData = CodingKeys(stringValue: "resourceData")
      static let iamPolicyData = CodingKeys(stringValue: "iamPolicyData")

      static let _knownKeys: Set<Swift.String> = [
        "resourceType",
        "resourceData",
        "iamPolicyData",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resourceType) {
        self.resourceType = value
      }
      self.resourceData = try container.decodeIfPresent(
        GoogleCloudWKT.Struct.self, forKey: .resourceData)
      self.iamPolicyData = try container.decodeIfPresent(
        GoogleIAMV1.Policy.self, forKey: .iamPolicyData)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.resourceType, forKey: .resourceType)
      try container.encodeIfPresent(self.resourceData, forKey: .resourceData)
      try container.encodeIfPresent(self.iamPolicyData, forKey: .iamPolicyData)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.securitycentermanagement.v1.SimulateSecurityHealthAnalyticsCustomModuleRequest.SimulatedResource"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.securitycentermanagement.v1.SimulateSecurityHealthAnalyticsCustomModuleRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
