// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The minimum set of fields needed to represent a simulated finding from a
/// Security Health Analytics custom module.
public struct SimulatedFinding: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The [relative resource name](https://google.aip.dev/122) of the
  /// finding, in one of the following formats:
  ///
  /// * `organizations/{organization_id}/sources/{source_id}/findings/{finding_id}`
  /// * `folders/{folder_id}/sources/{source_id}/findings/{finding_id}`
  /// * `projects/{project_id}/sources/{source_id}/findings/{finding_id}`
  public var name: Swift.String = Swift.String()

  /// The [relative resource name](https://google.aip.dev/122) of the source the
  /// finding belongs to. For example,
  /// `organizations/{organization_id}/sources/{source_id}`. This field is
  /// immutable after creation time.
  public var parent: Swift.String = Swift.String()

  /// For findings on Google Cloud resources, the
  /// [full resource name](https://google.aip.dev/122#full-resource-names) of the
  /// Google Cloud resource this finding is for. When the finding is for a
  /// non-Google Cloud resource, the value can be a customer or partner defined
  /// string. This field is immutable after creation time.
  public var resourceName: Swift.String = Swift.String()

  /// The additional taxonomy group within findings from a given source. For
  /// example, `XSS_FLASH_INJECTION`. This field is immutable after creation
  /// time.
  public var category: Swift.String = Swift.String()

  /// Output only. The state of the finding.
  public var state: SimulatedFinding.State = SimulatedFinding.State()

  /// Source-specific properties. These properties are managed by the source
  /// that writes the finding. The key names must be between 1 and 255
  /// characters; they must start with a letter and contain alphanumeric
  /// characters or underscores only.
  public var sourceProperties: [Swift.String: GoogleCloudWkt.Value] = [:]

  /// The time the finding was first detected. If an existing finding is updated,
  /// then this is the time the update occurred. If the finding is later
  /// resolved, then this time reflects when the finding was resolved.
  ///
  /// For example, if the finding represents an open firewall, this property
  /// captures the time the detector believes the firewall became open. The
  /// accuracy is determined by the detector.
  ///
  /// The event time must not be set to a value greater than the current
  /// timestamp.
  public var eventTime: GoogleCloudWkt.Timestamp? = nil

  /// The severity of the finding. This field is managed by the source that
  /// writes the finding.
  public var severity: SimulatedFinding.Severity = SimulatedFinding.Severity()

  /// The class of the finding.
  public var findingClass: SimulatedFinding.FindingClass = SimulatedFinding.FindingClass()

  /// Initialize a new instance of `SimulatedFinding`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SimulatedFinding().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The state of the finding.
  public enum State: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// The finding requires attention and has not been addressed yet.
    case active
    /// The finding has been fixed, triaged as a non-issue, or otherwise
    /// addressed and is no longer active.
    case inactive
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .inactive: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .inactive: return "INACTIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "INACTIVE": self = .inactive
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .inactive
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .inactive: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The severity of the finding.
  public enum Severity: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// For vulnerabilities: A critical vulnerability is easily discoverable by
    /// an external actor, exploitable, and results in the direct ability to
    /// execute arbitrary code, exfiltrate data, and otherwise gain additional
    /// access and privileges to cloud resources and workloads. Examples include
    /// publicly accessible unprotected user data and public SSH access with weak
    /// or no passwords.
    ///
    /// For threats: Indicates a threat that is able to access, modify, or delete
    /// data or execute unauthorized code within existing resources.
    case critical
    /// For vulnerabilities: A high-risk vulnerability can be easily discovered
    /// and exploited in combination with other vulnerabilities in order to gain
    /// direct access and the ability to execute arbitrary code, exfiltrate data,
    /// and otherwise gain additional access and privileges to cloud resources
    /// and workloads. An example is a database with weak or no passwords that is
    /// only accessible internally. This database could easily be compromised by
    /// an actor that had access to the internal network.
    ///
    /// For threats: Indicates a threat that is able to create new computational
    /// resources in an environment but not able to access data or execute code
    /// in existing resources.
    case high
    /// For vulnerabilities: A medium-risk vulnerability could be used by an
    /// actor to gain access to resources or privileges that enable them to
    /// eventually (through multiple steps or a complex exploit) gain access and
    /// the ability to execute arbitrary code or exfiltrate data. An example is a
    /// service account with access to more projects than it should have. If an
    /// actor gains access to the service account, they could potentially use
    /// that access to manipulate a project the service account was not intended
    /// to.
    ///
    /// For threats: Indicates a threat that is able to cause operational impact
    /// but may not access data or execute unauthorized code.
    case medium
    /// For vulnerabilities: A low-risk vulnerability hampers a security
    /// organization's ability to detect vulnerabilities or active threats in
    /// their deployment, or prevents the root cause investigation of security
    /// issues. An example is monitoring and logs being disabled for resource
    /// configurations and access.
    ///
    /// For threats: Indicates a threat that has obtained minimal access to an
    /// environment but is not able to access data, execute code, or create
    /// resources.
    case low
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .critical: return 1
      case .high: return 2
      case .medium: return 3
      case .low: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SEVERITY_UNSPECIFIED"
      case .critical: return "CRITICAL"
      case .high: return "HIGH"
      case .medium: return "MEDIUM"
      case .low: return "LOW"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Severity/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SEVERITY_UNSPECIFIED": self = .unspecified
      case "CRITICAL": self = .critical
      case "HIGH": self = .high
      case "MEDIUM": self = .medium
      case "LOW": self = .low
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Severity/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .critical
      case 2: self = .high
      case 3: self = .medium
      case 4: self = .low
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .critical: return try container.encode(1)
      case .high: return try container.encode(2)
      case .medium: return try container.encode(3)
      case .low: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Represents what kind of finding it is.
  public enum FindingClass: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Describes unwanted or malicious activity.
    case threat
    /// Describes a potential weakness in software that increases risk to
    /// confidentiality, integrity, and availability.
    case vulnerability
    /// Describes a potential weakness in cloud resource or asset configuration
    /// that increases risk.
    case misconfiguration
    /// Describes a security observation that is for informational purposes.
    case observation
    /// Describes an error that prevents Security Command Center from working
    /// correctly.
    case sccError
    /// Describes a potential security risk due to a change in the security
    /// posture.
    case postureViolation
    /// Describes a combination of security issues that represent a more severe
    /// security problem when taken together.
    case toxicCombination
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .threat: return 1
      case .vulnerability: return 2
      case .misconfiguration: return 3
      case .observation: return 4
      case .sccError: return 5
      case .postureViolation: return 6
      case .toxicCombination: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "FINDING_CLASS_UNSPECIFIED"
      case .threat: return "THREAT"
      case .vulnerability: return "VULNERABILITY"
      case .misconfiguration: return "MISCONFIGURATION"
      case .observation: return "OBSERVATION"
      case .sccError: return "SCC_ERROR"
      case .postureViolation: return "POSTURE_VIOLATION"
      case .toxicCombination: return "TOXIC_COMBINATION"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FindingClass/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "FINDING_CLASS_UNSPECIFIED": self = .unspecified
      case "THREAT": self = .threat
      case "VULNERABILITY": self = .vulnerability
      case "MISCONFIGURATION": self = .misconfiguration
      case "OBSERVATION": self = .observation
      case "SCC_ERROR": self = .sccError
      case "POSTURE_VIOLATION": self = .postureViolation
      case "TOXIC_COMBINATION": self = .toxicCombination
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FindingClass/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .threat
      case 2: self = .vulnerability
      case 3: self = .misconfiguration
      case 4: self = .observation
      case 5: self = .sccError
      case 6: self = .postureViolation
      case 7: self = .toxicCombination
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .threat: return try container.encode(1)
      case .vulnerability: return try container.encode(2)
      case .misconfiguration: return try container.encode(3)
      case .observation: return try container.encode(4)
      case .sccError: return try container.encode(5)
      case .postureViolation: return try container.encode(6)
      case .toxicCombination: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.securitycentermanagement.v1.SimulatedFinding"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
