// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [SecurityCenterManagement.UpdateSecurityCenterService][google.cloud.securitycentermanagement.v1.SecurityCenterManagement.UpdateSecurityCenterService].
///
/// [google.cloud.securitycentermanagement.v1.SecurityCenterManagement.UpdateSecurityCenterService]: <doc:SecurityCenterManagementClient/updateSecurityCenterService(request:options:)>
public struct UpdateSecurityCenterServiceRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The updated service.
  public var securityCenterService: SecurityCenterService? = nil

  /// Required. The fields to update. Accepts the following values:
  ///
  /// * `intended_enablement_state`
  /// * `modules`
  ///
  /// If omitted, then all eligible fields are updated.
  public var updateMask: GoogleWKT.WKTFieldMask? = nil

  /// Optional. When set to `true`, the request will be validated (including IAM
  /// checks), but no service will be updated. An `OK` response indicates that
  /// the request is valid, while an error response indicates that the request is
  /// invalid.
  ///
  /// If the request is valid, a subsequent request to update the service could
  /// still fail for one of the following reasons:
  ///
  /// *  The state of your cloud resources changed; for example, you lost a
  ///    required IAM permission
  /// *  An error occurred during update of the service
  ///
  /// Defaults to `false`.
  public var validateOnly: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateSecurityCenterServiceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateSecurityCenterServiceRequest().with { $0.securityCenterService = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let securityCenterService = CodingKeys(stringValue: "securityCenterService")
    static let updateMask = CodingKeys(stringValue: "updateMask")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")

    static let _knownKeys: Set<Swift.String> = [
      "securityCenterService",
      "updateMask",
      "validateOnly",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.securityCenterService = try container.decodeIfPresent(
      SecurityCenterService.self, forKey: .securityCenterService)
    self.updateMask = try container.decodeIfPresent(
      GoogleWKT.WKTFieldMask.self, forKey: .updateMask)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.securityCenterService, forKey: .securityCenterService)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.securitycentermanagement.v1.UpdateSecurityCenterServiceRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
