// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for
/// [SecurityCenterManagement.UpdateSecurityHealthAnalyticsCustomModule][google.cloud.securitycentermanagement.v1.SecurityCenterManagement.UpdateSecurityHealthAnalyticsCustomModule].
///
/// [google.cloud.securitycentermanagement.v1.SecurityCenterManagement.UpdateSecurityHealthAnalyticsCustomModule]: <doc:SecurityCenterManagementClient/updateSecurityHealthAnalyticsCustomModule(request:options:)>
public struct UpdateSecurityHealthAnalyticsCustomModuleRequest: Codable, Equatable, GoogleCloudWKT
    ._AnyPackable,
  Sendable
{
  /// Required. The fields to update. The following values are valid:
  ///
  /// * `custom_config`
  /// * `enablement_state`
  ///
  /// If you omit this field or set it to the wildcard value `*`, then all
  /// eligible fields are updated.
  public var updateMask: GoogleCloudWKT.FieldMask? = nil

  /// Required. The resource being updated.
  public var securityHealthAnalyticsCustomModule: SecurityHealthAnalyticsCustomModule? = nil

  /// Optional. When set to `true`, the request will be validated (including IAM
  /// checks), but no module will be updated. An `OK` response indicates that the
  /// request is valid, while an error response indicates that the request is
  /// invalid.
  ///
  /// If the request is valid, a subsequent request to update the module could
  /// still fail for one of the following reasons:
  ///
  /// *  The state of your cloud resources changed; for example, you lost a
  ///    required IAM permission
  /// *  An error occurred during creation of the module
  ///
  /// Defaults to `false`.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `UpdateSecurityHealthAnalyticsCustomModuleRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateSecurityHealthAnalyticsCustomModuleRequest().with { $0.updateMask = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.securitycentermanagement.v1.UpdateSecurityHealthAnalyticsCustomModuleRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
