// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Response message for
/// [SecurityCenterManagement.ValidateEventThreatDetectionCustomModule][google.cloud.securitycentermanagement.v1.SecurityCenterManagement.ValidateEventThreatDetectionCustomModule].
///
/// [google.cloud.securitycentermanagement.v1.SecurityCenterManagement.ValidateEventThreatDetectionCustomModule]: <doc:SecurityCenterManagementClient/validateEventThreatDetectionCustomModule(request:options:)>
public struct ValidateEventThreatDetectionCustomModuleResponse: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// A list of errors returned by the validator. If the list is empty, there
  /// were no errors.
  public var errors:
    [ValidateEventThreatDetectionCustomModuleResponse.CustomModuleValidationError] = []

  /// Initialize a new instance of `ValidateEventThreatDetectionCustomModuleResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ValidateEventThreatDetectionCustomModuleResponse().with { $0.errors = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// An error encountered while validating the uploaded configuration of an
  /// Event Threat Detection custom module.
  public struct CustomModuleValidationError: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// A human-readable description of the error.
    public var description: Swift.String = Swift.String()

    /// The path, in [RFC 6901: JSON
    /// Pointer](https://datatracker.ietf.org/doc/html/rfc6901) format, to the
    /// field that failed validation. Omitted if no specific field is affected.
    public var fieldPath: Swift.String = Swift.String()

    /// The initial position of the error in the uploaded text version of the
    /// module. Omitted if no specific position applies, or if the position could
    /// not be computed.
    public var start: ValidateEventThreatDetectionCustomModuleResponse.Position? = nil

    /// The end position of the error in the uploaded text version of the module.
    /// Omitted if no specific position applies, or if the position could not be
    /// computed.
    public var end: ValidateEventThreatDetectionCustomModuleResponse.Position? = nil

    /// Initialize a new instance of `CustomModuleValidationError`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CustomModuleValidationError().with { $0.description = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.securitycentermanagement.v1.ValidateEventThreatDetectionCustomModuleResponse.CustomModuleValidationError"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A position in the uploaded text version of a module.
  public struct Position: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The line position in the text.
    public var lineNumber: Swift.Int32 = Swift.Int32()

    /// The column position in the line.
    public var columnNumber: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `Position`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Position().with { $0.lineNumber = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.securitycentermanagement.v1.ValidateEventThreatDetectionCustomModuleResponse.Position"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.securitycentermanagement.v1.ValidateEventThreatDetectionCustomModuleResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
