// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Response message for
/// [SecurityCenterManagement.ValidateEventThreatDetectionCustomModule][google.cloud.securitycentermanagement.v1.SecurityCenterManagement.ValidateEventThreatDetectionCustomModule].
///
/// [google.cloud.securitycentermanagement.v1.SecurityCenterManagement.ValidateEventThreatDetectionCustomModule]: <doc:SecurityCenterManagementClient/validateEventThreatDetectionCustomModule(request:options:)>
public struct ValidateEventThreatDetectionCustomModuleResponse: Codable, Equatable, GoogleWKT
    ._AnyPackable,
  Sendable
{
  /// A list of errors returned by the validator. If the list is empty, there
  /// were no errors.
  public var errors:
    [ValidateEventThreatDetectionCustomModuleResponse.CustomModuleValidationError] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ValidateEventThreatDetectionCustomModuleResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ValidateEventThreatDetectionCustomModuleResponse().with { $0.errors = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let errors = CodingKeys(stringValue: "errors")

    static let _knownKeys: Set<Swift.String> = [
      "errors"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [ValidateEventThreatDetectionCustomModuleResponse.CustomModuleValidationError].self,
      forKey: .errors)
    {
      self.errors = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.errors, forKey: .errors)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// An error encountered while validating the uploaded configuration of an
  /// Event Threat Detection custom module.
  public struct CustomModuleValidationError: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A human-readable description of the error.
    public var description: Swift.String = Swift.String()

    /// The path, in [RFC 6901: JSON
    /// Pointer](https://datatracker.ietf.org/doc/html/rfc6901) format, to the
    /// field that failed validation. Omitted if no specific field is affected.
    public var fieldPath: Swift.String = Swift.String()

    /// The initial position of the error in the uploaded text version of the
    /// module. Omitted if no specific position applies, or if the position could
    /// not be computed.
    public var start: ValidateEventThreatDetectionCustomModuleResponse.Position? = nil

    /// The end position of the error in the uploaded text version of the module.
    /// Omitted if no specific position applies, or if the position could not be
    /// computed.
    public var end: ValidateEventThreatDetectionCustomModuleResponse.Position? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CustomModuleValidationError`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CustomModuleValidationError().with { $0.description = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let description = CodingKeys(stringValue: "description")
      static let fieldPath = CodingKeys(stringValue: "fieldPath")
      static let start = CodingKeys(stringValue: "start")
      static let end = CodingKeys(stringValue: "end")

      static let _knownKeys: Set<Swift.String> = [
        "description",
        "fieldPath",
        "start",
        "end",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
        self.description = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fieldPath) {
        self.fieldPath = value
      }
      self.start = try container.decodeIfPresent(
        ValidateEventThreatDetectionCustomModuleResponse.Position.self, forKey: .start)
      self.end = try container.decodeIfPresent(
        ValidateEventThreatDetectionCustomModuleResponse.Position.self, forKey: .end)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.description, forKey: .description)
      try container.encode(self.fieldPath, forKey: .fieldPath)
      try container.encodeIfPresent(self.start, forKey: .start)
      try container.encodeIfPresent(self.end, forKey: .end)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.securitycentermanagement.v1.ValidateEventThreatDetectionCustomModuleResponse.CustomModuleValidationError"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A position in the uploaded text version of a module.
  public struct Position: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The line position in the text.
    public var lineNumber: Swift.Int32 = Swift.Int32()

    /// The column position in the line.
    public var columnNumber: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Position`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Position().with { $0.lineNumber = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let lineNumber = CodingKeys(stringValue: "lineNumber")
      static let columnNumber = CodingKeys(stringValue: "columnNumber")

      static let _knownKeys: Set<Swift.String> = [
        "lineNumber",
        "columnNumber",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .lineNumber) {
        self.lineNumber = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .columnNumber) {
        self.columnNumber = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.lineNumber, forKey: .lineNumber)
      try container.encode(self.columnNumber, forKey: .columnNumber)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.securitycentermanagement.v1.ValidateEventThreatDetectionCustomModuleResponse.Position"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.securitycentermanagement.v1.ValidateEventThreatDetectionCustomModuleResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
